/* Anlar (moments) yönetimi — 2026-10-09. Okuma: yonetim_anlar_* (moderation + MFA). Kaldırma: mevcut yonetim_icerik_sil. */
(()=>{'use strict';let ctx=null,seq=0;const $=s=>document.querySelector(s),fmt=x=>new Intl.NumberFormat('tr-TR').format(Number(x)||0);
const SIRA=[['yeni','En yeni'],['begeni','Beğeni'],['hediye','Hediye'],['sikayet','Şikayet']],FILTRE=[['aktif','Yayında'],['tumu','Tümü'],['kaldirilan','Kaldırılan'],['video','Video'],['foto','Fotoğraf'],['yarisma','Yarışma']];
const yetkili=c=>c&&(c.caps.admin||c.caps.sanction);
const hataMetni=(c,e)=>(e&&(e.code==='PGRST202'||/Could not find the function/i.test(e.message||'')))?'Anlar sunucu güncellemesi henüz uygulanmadı.':c.errorText(e);
function init(c){stop();ctx=c;const host=$('#anlar-nav');if(host)host.innerHTML=yetkili(c)?'<a class="menu" href="#anlar" data-sayfa="anlar"><span>Anlar</span></a>':'';}
function stop(){seq++;ctx=null;$('#anlar-nav')?.replaceChildren();$('#s-anlar')?.replaceChildren();}
function sayfa(baslik){const root=$('#s-anlar');document.querySelectorAll('.workspace > [id^="s-"]').forEach(e=>e.classList.toggle('hidden',e!==root));$('#uyg nav')?.classList.remove('open');const rn=$('#route-name');if(rn)rn.textContent=baslik;document.querySelectorAll('nav a.menu').forEach(a=>a.classList.toggle('aktif',a.dataset.sayfa==='anlar'));return root;}
function medya(c,m){const v=m.video_url,i=m.image_url;if(v&&/^https:\/\//i.test(v))return `<video src="${c.esc(c.safeUrl(v))}" controls preload="metadata" style="max-width:100%;max-height:320px"></video>`;if(i&&/^https:\/\//i.test(i))return `<img src="${c.esc(c.safeUrl(i))}" alt="" loading="lazy" referrerpolicy="no-referrer" style="max-width:100%;max-height:320px">`;return '<span class="meta">medya yok</span>';}
function gerekce(c,baslik){return new Promise(res=>{const d=document.createElement('dialog');d.innerHTML=`<form method="dialog"><h3>${c.esc(baslik)}</h3><label>Gerekçe (3–300)<textarea name="g" maxlength="300" rows="3" required></textarea></label><p class="meta">İşlem kütüğe yazılır; içerik sahibine geri alınamaz şekilde kaldırılır.</p><div class="actions"><button value="iptal">Vazgeç</button><button value="ok" class="danger">Kaldır</button></div></form>`;document.body.append(d);d.addEventListener('close',()=>{const g=d.querySelector('textarea').value.trim();d.remove();res(d.returnValue==='ok'&&g.length>=3?g:null);});d.showModal();});}
async function kaldir(c,tur,id,sonra){const g=await gerekce(c,tur==='moment'?'Anı kaldır':'Yorumu kaldır');if(!g)return;try{await c.rpc('yonetim_icerik_sil',{p_tur:tur,p_idler:[id],p_neden:g});c.toast('Kaldırıldı.');sonra();}catch(e){c.toast(({CONTENT_PROTECTED:'Yarışma sonuç kartı kaldırılamaz.',PERSONEL_MUAF:'Bu hesap personel muafiyetinde.'})[e.message]||c.errorText(e));}}
async function liste(params){const c=ctx,n=++seq,root=sayfa('Anlar');const p=Math.max(0,Number(params.get('sayfa'))||0),sira=params.get('sira')||'yeni',filtre=params.get('filtre')||'aktif',q=params.get('q')||'';root.innerHTML='<h1>Anlar</h1><div class="skeleton"></div>';const ok=()=>ctx===c&&n===seq;
 try{const [o,a]=await Promise.all([c.rpc('yonetim_anlar_ozet'),c.rpc('yonetim_anlar_akisi',{p_sirala:sira,p_filtre:filtre,p_ara:q,p_limit:25,p_offset:p*25})]);if(!ok())return;
 const dn=o.deneme7g||{},hat=(o.son_hatalar||[]).map(h=>`<tr><td>${c.esc(h.hata||'—')}</td><td>${c.esc(h.medya||'—')}</td><td>${c.esc(h.uygulama_surumu||'—')}</td><td>${fmt(h.adet)}</td><td>${c.date(h.son)}</td></tr>`).join('');
 const yr=o.yarisma?`${c.esc(o.yarisma.status)} · ${c.date(o.yarisma.starts_at)} → ${c.date(o.yarisma.ends_at)}`:'—';
 root.innerHTML=`<div class="page-title"><div><div class="eyebrow">İÇERİK / ANLAR</div><h1>Anlar</h1><p>Akış, moderasyon, yarışmalar ve paylaşım sağlığı.</p></div><a class="chip" href="#anlar-yarisma">Yarışmalar →</a></div>
 <div class="metrics">${[['Yayında',o.toplam],['Son 7 gün',o.son7g],['Son 30 gün',o.son30g],['Şikayet',o.acik_sikayet]].map(([k,v])=>`<div class="metric"><b>${fmt(v)}</b><span>${k}</span></div>`).join('')}<div class="metric"><b>${o.son_paylasim?c.date(o.son_paylasim):'—'}</b><span>Son kullanıcı paylaşımı</span></div><div class="metric"><b style="font-size:13px">${yr}</b><span>Güncel yarışma</span></div></div>
 <section class="panel"><h3>Paylaşım denemeleri (7 gün)</h3><p>Başlayan <b>${fmt(dn.baslayan)}</b> · Kaydedilen <b>${fmt(dn.kaydedilen)}</b> · Hatalı <b>${fmt(dn.hatali)}</b> · Vazgeçilen <b>${fmt(dn.iptal)}</b></p>${hat?`<table><thead><tr><th>Hata</th><th>Medya</th><th>Sürüm</th><th>Adet</th><th>Son</th></tr></thead><tbody>${hat}</tbody></table>`:'<p class="meta">Son 7 günde kaydedilmiş hata yok (kayıt, telemetrili uygulama sürümüyle başlar).</p>'}</section>
 <section class="panel"><form class="org-filters"><label>Ara (takma ad, ID, açıklama)<input name="q" maxlength="60" value="${c.esc(q)}"></label><label>Sırala<select name="sira">${SIRA.map(([k,v])=>`<option value="${k}" ${k===sira?'selected':''}>${v}</option>`).join('')}</select></label><label>Filtre<select name="filtre">${FILTRE.map(([k,v])=>`<option value="${k}" ${k===filtre?'selected':''}>${v}</option>`).join('')}</select></label><button class="primary">Uygula</button></form>
 <table><thead><tr><th>Tarih</th><th>Sahibi</th><th>Açıklama</th><th>Tür</th><th>♥</th><th>💬</th><th>🎁</th><th>⚑</th><th>Durum</th></tr></thead><tbody>${(a.rows||[]).map(m=>`<tr data-id="${c.esc(m.id)}" style="cursor:pointer"><td>${c.date(m.created_at)}</td><td>${c.esc(m.nickname||'—')} <span class="meta">${c.esc(m.display_id??'')}</span></td><td>${c.esc((m.caption||'').slice(0,80))}</td><td>${c.esc(m.type==='contest_result'?'yarışma kartı':(m.video_url?'video':'foto'))}</td><td>${fmt(m.like_count)}</td><td>${fmt(m.comment_count)}</td><td>${fmt(m.hediye)}</td><td>${fmt(m.sikayet)}</td><td>${m.deleted_at?'<span class="rozet">kaldırıldı</span>':'yayında'}</td></tr>`).join('')||'<tr><td colspan="9" class="meta">Kayıt yok.</td></tr>'}</tbody></table>
 <div class="actions"><button data-prev ${p?'':'disabled'}>← Önceki</button><span class="meta">${fmt(a.total)} kayıt · sayfa ${p+1}</span><button data-next ${(p+1)*25<a.total?'':'disabled'}>Sonraki →</button></div></section>`;
 const git=o2=>{const u=new URLSearchParams({q,sira,filtre,sayfa:String(o2.sayfa??p),...o2});location.hash='anlar?'+u.toString();};
 root.querySelector('form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);git({q:String(f.get('q')||''),sira:String(f.get('sira')),filtre:String(f.get('filtre')),sayfa:'0'});};
 root.querySelector('[data-prev]').onclick=()=>git({sayfa:String(p-1)});root.querySelector('[data-next]').onclick=()=>git({sayfa:String(p+1)});
 root.querySelectorAll('tr[data-id]').forEach(tr=>tr.onclick=()=>{location.hash='anlar/'+tr.dataset.id;});
 }catch(e){if(ok())root.innerHTML=`<h1>Anlar</h1><p class="hata">${c.esc(hataMetni(c,e))}</p>`;}}
async function detay(id){const c=ctx,n=++seq,root=sayfa('An detayı');root.innerHTML='<div class="skeleton"></div>';const ok=()=>ctx===c&&n===seq;
 try{const d=await c.rpc('yonetim_an_detay',{p_id:id});if(!ok())return;const m=d.an;
 root.innerHTML=`<div class="page-title"><a href="#anlar">← Anlar</a><h1>${c.esc(m.nickname||'—')} <span class="meta">${c.esc(m.display_id??'')}</span></h1><p>${c.date(m.created_at)} · ${c.esc(m.visibility||'')} · ${m.deleted_at?'kaldırıldı '+c.date(m.deleted_at):'yayında'}</p></div>
 <section class="panel">${medya(c,m)}<p>${c.esc(m.caption||'')}</p><p class="meta">♥ ${fmt(m.like_count)} · 💬 ${fmt(m.comment_count)} · 👁 ${fmt(m.view_count)} · ↗ ${fmt(m.share_count)} · 🔖 ${fmt(m.save_count)}</p>${!m.deleted_at&&m.type!=='contest_result'?'<button class="danger" data-kaldir>Anı kaldır</button>':''}<a class="chip" href="#kullanici/${c.esc(m.user_id)}">Kullanıcı profili</a></section>
 <section class="panel"><h3>Şikayetler (${d.sikayetler.length})</h3>${d.sikayetler.map(r=>`<p><b>${c.esc(r.reason)}</b> · ${c.esc(r.reporter||'—')} · ${c.date(r.created_at)}${r.note?'<br>'+c.esc(r.note):''}</p>`).join('')||'<p class="meta">Şikayet yok.</p>'}</section>
 <section class="panel"><h3>Hediyeler</h3>${d.hediyeler.map(g=>`<span class="chip">${c.esc(String(g.gift_id).slice(0,8))} × ${fmt(g.adet)} (${fmt(g.gonderen)} kişi)</span>`).join(' ')||'<p class="meta">Hediye yok.</p>'}</section>
 <section class="panel"><h3>Yorumlar (son ${d.yorumlar.length})</h3><table><tbody>${d.yorumlar.map(y=>`<tr><td>${c.date(y.created_at)}</td><td>${c.esc(y.nickname||'—')}</td><td>${c.esc(y.text||'')}</td><td>${y.deleted_at?'<span class="rozet">kaldırıldı</span>':`<button class="danger" data-yorum="${c.esc(y.id)}">Kaldır</button>`}</td></tr>`).join('')||'<tr><td class="meta">Yorum yok.</td></tr>'}</tbody></table></section>`;
 root.querySelector('[data-kaldir]')?.addEventListener('click',()=>kaldir(c,'moment',m.id,()=>detay(id)));
 root.querySelectorAll('[data-yorum]').forEach(b=>b.onclick=()=>kaldir(c,'moment_comment',b.dataset.yorum,()=>detay(id)));
 }catch(e){if(ok())root.innerHTML=`<a href="#anlar">← Anlar</a><p class="hata">${c.esc(hataMetni(c,e))}</p>`;}}
async function yarismalar(params){const c=ctx,n=++seq,root=sayfa('An yarışmaları');const p=Math.max(0,Number(params.get('sayfa'))||0);root.innerHTML='<div class="skeleton"></div>';const ok=()=>ctx===c&&n===seq;
 try{const d=await c.rpc('yonetim_an_yarismalari',{p_limit:20,p_offset:p*20});if(!ok())return;
 root.innerHTML=`<div class="page-title"><a href="#anlar">← Anlar</a><h1>An yarışmaları</h1></div><section class="panel"><table><thead><tr><th>Başlangıç</th><th>Bitiş</th><th>Durum</th><th>Katılımcı</th><th>Ödenen coin</th><th>Geri alınan</th></tr></thead><tbody>${(d.rows||[]).map(y=>`<tr data-id="${c.esc(y.id)}" style="cursor:pointer"><td>${c.date(y.starts_at)}</td><td>${c.date(y.ends_at)}</td><td>${c.esc(y.status)}${y.paid_at?' · ödendi':''}</td><td>${fmt(y.katilimci)}</td><td>${fmt(y.odenen_coin)}</td><td>${fmt(y.geri_alinan)}</td></tr>`).join('')||'<tr><td colspan="6" class="meta">Yarışma yok.</td></tr>'}</tbody></table></section>`;
 root.querySelectorAll('tr[data-id]').forEach(tr=>tr.onclick=()=>{location.hash='anlar-yarisma/'+tr.dataset.id;});
 }catch(e){if(ok())root.innerHTML=`<p class="hata">${c.esc(hataMetni(c,e))}</p>`;}}
async function yarisma(id){const c=ctx,n=++seq,root=sayfa('Yarışma detayı');root.innerHTML='<div class="skeleton"></div>';const ok=()=>ctx===c&&n===seq;
 try{const d=await c.rpc('yonetim_an_yarisma_detay',{p_contest:id});if(!ok())return;const y=d.yarisma;
 root.innerHTML=`<div class="page-title"><a href="#anlar-yarisma">← Yarışmalar</a><h1>Yarışma</h1><p>${c.date(y.starts_at)} → ${c.date(y.ends_at)} · ${c.esc(y.status)}</p></div>
 <section class="panel"><h3>Sıralama (ilk 50)</h3><table><thead><tr><th>#</th><th>Kullanıcı</th><th>Toplam</th><th>♥</th><th>💬</th><th>↗</th><th>🔖</th><th>👁</th><th>🎁</th></tr></thead><tbody>${d.siralama.map(s=>`<tr><td>${s.rank??'—'}${s.is_preview?' <span class="meta">önizleme</span>':''}</td><td>${c.esc(s.nickname||'—')} <span class="meta">${c.esc(s.display_id??'')}</span></td><td>${fmt(s.total_pts)}</td><td>${fmt(s.like_pts)}</td><td>${fmt(s.comment_pts)}</td><td>${fmt(s.share_pts)}</td><td>${fmt(s.save_pts)}</td><td>${fmt(s.view_pts)}</td><td>${fmt(s.gift_pts)}</td></tr>`).join('')||'<tr><td colspan="9" class="meta">Puan yok.</td></tr>'}</tbody></table></section>
 <section class="panel"><h3>Ödemeler</h3>${d.odemeler.map(o=>`<p>#${o.rank} ${c.esc(o.nickname||'—')} · ${fmt(o.coin_amount)} coin · ${o.paid_at?c.date(o.paid_at):'bekliyor'}</p>`).join('')||'<p class="meta">Ödeme yok.</p>'}<h3>Ödül kayıtları</h3>${d.oduller.map(w=>`<p>#${w.rank} · ${c.date(w.awarded_at)}${w.revoked_at?' · <b>geri alındı</b> '+c.date(w.revoked_at):''}</p>`).join('')||'<p class="meta">Kayıt yok.</p>'}</section>`;
 }catch(e){if(ok())root.innerHTML=`<p class="hata">${c.esc(hataMetni(c,e))}</p>`;}}
function route(hash){const [path,q]=hash.split('?'),params=new URLSearchParams(q||''),[a,b]=path.split('/');if(a!=='anlar'&&a!=='anlar-yarisma')return false;if(!yetkili(ctx)){location.hash='ozet';return true;}
 if(a==='anlar'&&b)detay(b);else if(a==='anlar')liste(params);else if(b)yarisma(b);else yarismalar(params);return true;}
window.PuffyAnlar={init,stop,route};})();
