/* Karar merkezi: mevcut karar RPC'leri; EK3 taslağı gereken yollar açıkça belirtilir. */
(() => {
 'use strict';
 const defs={
  ajans_kurma:{label:'Ajans kurma',gate:c=>c.admin,rpc:'list_agency_creation_requests',args:{p_status:'pending',p_limit:200}},
  ajans_logo:{label:'Ajans logosu',gate:c=>c.agency,rpc:'list_agency_avatar_requests',args:{p_status:'pending',p_limit:200}},
  etkinlik:{label:'Etkinlik',gate:c=>c.event,rpc:'etkinlik_bekleyenler',args:{p_limit:200}},
  oda_kapagi:{label:'Oda kapağı',gate:c=>c.cover,rpc:'yonetim_oda_kapagi_bekleyenler',paged:true},
  oda_temasi:{label:'Oda teması',gate:c=>c.admin,rpc:'room_custom_theme_queue'},
  bayi_yukleme:{label:'Bayi yükleme',gate:c=>c.owner&&c.admin,rpc:'admin_list_dealer_topups',args:{p_status:'pending',p_limit:500}},
  para_cekme:{label:'Para çekme',gate:c=>c.admin&&c.owner,rpc:'yonetim_para_cekme_bekleyenler',paged:true},
  hesap_silme:{label:'Hesap silme',gate:c=>c.actions?.account_manage===true,rpc:'yonetim_hesap_silme_bekleyenler',paged:true},
  ozel_id:{label:'Özel ID',gate:c=>c.admin,rpc:'yonetim_ozel_id_bekleyenler',paged:true},
  call_host:{label:'Call Host başvuru',gate:c=>c.admin,rpc:'call_host_basvurulari',args:{p_durum:'bekliyor',p_limit:200}},
  call_host_foto:{label:'Call Host fotoğraf',gate:c=>c.admin,rpc:'call_host_foto_bekleyenler'}
 };
 let ctx,epoch=0,timer,polling=false,counts={},events=[],base=false,openKey='',page=0,lastRows=[],eventCursor=null;
 const $=s=>document.querySelector(s), fmt=n=>new Intl.NumberFormat('tr-TR').format(n||0);
 const path=k=>k==='short'?'#shorts':k==='sikayet'?'#sikayet':'#onay/'+k;
 const label=k=>defs[k]?.label||({short:'Shorts',sikayet:'Şikâyet'}[k]||k);
 const allowed=k=>k==='short'?ctx?.caps.admin:k==='sikayet'?ctx?.caps.moderator:defs[k]?.gate(ctx?.caps||{});
 const rowsOf=d=>Array.isArray(d)?d:d?.requests||d?.rows||[];
 const safeImage=(src,title,type)=>window.PuffyModeration.media(src,title,type,ctx.esc,ctx.safeUrl);
 const pairs=o=>`<dl class="key-values">${Object.entries(o).map(([k,v])=>`<div><dt>${ctx.esc(k)}</dt><dd>${ctx.esc(v??'—')}</dd></div>`).join('')}</dl>`;
 const nameOf=r=>r.name||r.agency_name||r.title||r.nickname||r.applicant_nickname||r.dealer?.nickname||r.room_name||r.uploader_nickname||r.vanity_id||'Başvuru';
 const userOf=r=>r.applicant_id||r.requested_by||r.user_id||r.dealer?.id;
 function init(c){stop();ctx=c;counts={};events=[];eventCursor=null;base=false;nav();top();offerNotifications();poll();document.addEventListener('visibilitychange',visibility);}
 function stop(){epoch++;clearTimeout(timer);document.removeEventListener('visibilitychange',visibility);ctx=null;polling=false;base=false;document.title='Puffy Yönetim';$('#approval-alert')?.remove();$('#approval-bell-wrap')?.remove();}
 function nav(){const host=$('#approval-nav');if(!host)return;host.innerHTML='<div class="nav-caption">Onaylar</div>'+Object.entries(defs).filter(([k])=>allowed(k)).map(([k,d])=>`<a class="menu" href="${path(k)}" data-sayfa="onay/${k}"><span>${ctx.esc(d.label)}</span><span class="rozet sifir" data-count="${k}">0</span></a>`).join('');}
 function top(){const host=$('#panel-topbar');host.insertAdjacentHTML('beforeend','<div id="approval-bell-wrap"><button id="approval-bell" aria-label="Başvuru bildirimleri" aria-expanded="false">🔔 <span id="approval-total">0</span></button><section id="approval-events" class="hidden" aria-label="Başvuru bildirimleri"></section></div>');$('#approval-bell').onclick=()=>{const box=$('#approval-events'),show=box.classList.toggle('hidden')===false;$('#approval-bell').setAttribute('aria-expanded',String(show));renderEvents();};}
 function offerNotifications(){if(!('Notification' in window)||Notification.permission!=='default')return;try{if(localStorage.getItem('puffy_approval_notice_offered'))return;localStorage.setItem('puffy_approval_notice_offered','yes');}catch{}const a=document.createElement('div');a.id='approval-alert';a.className='approval-alert';a.innerHTML='<span>Yeni başvuruları masaüstünde de gör.</span><div><button data-enable>Masaüstü bildirimlerini aç</button><button data-dismiss aria-label="Uyarıyı kapat">×</button></div>';$('#panel-topbar').after(a);a.querySelector('[data-dismiss]').onclick=()=>a.remove();a.querySelector('[data-enable]').onclick=async()=>{await Notification.requestPermission();a.remove();};}
 function readPreference(){try{return localStorage.getItem('puffy_approval_sound')==='on';}catch{return false;}}
 function renderEvents(){if(!ctx)return;const box=$('#approval-events');box.innerHTML='<h3>Yeni başvurular</h3>'+events.map(e=>`<a href="${path(e.key)}"><strong>${ctx.esc(label(e.key))} · +${e.n}</strong><small>${ctx.esc(ctx.date(e.at))}</small></a>`).join('')+(events.length?'':'<p>Bu oturumda yeni başvuru yok.</p>')+`<label><input type="checkbox" id="approval-sound" ${readPreference()?'checked':''}> Bildirim sesi</label><button id="approval-desktop">Masaüstü bildirimlerini aç</button>`;$('#approval-sound').onchange=e=>{try{localStorage.setItem('puffy_approval_sound',e.target.checked?'on':'off');}catch{ctx.toast('Ses tercihi bu tarayıcıda kaydedilemiyor.');}};$('#approval-desktop').onclick=async()=>{if(!('Notification' in window)){ctx.toast('Tarayıcın masaüstü bildirimlerini desteklemiyor.');return;}const p=await Notification.requestPermission();ctx.toast(p==='granted'?'Masaüstü bildirimleri açık.':'Bildirim izni verilmedi; zil bildirimleri devam eder.');};}
 function signal(key,n){events.unshift({key,n,at:new Date().toISOString()});events=events.slice(0,10);$('#approval-alert')?.remove();const a=document.createElement('div');a.id='approval-alert';a.className='approval-alert';a.setAttribute('role','status');a.innerHTML=`<a href="${path(key)}">Yeni başvuru: ${ctx.esc(label(key))} · +${n} →</a><button aria-label="Uyarıyı kapat">×</button>`;$('#panel-topbar').after(a);a.querySelector('button').onclick=()=>a.remove();if(readPreference())try{const Audio=window.AudioContext||window.webkitAudioContext,ac=new Audio(),osc=ac.createOscillator(),gain=ac.createGain();osc.frequency.value=660;gain.gain.value=.035;osc.connect(gain);gain.connect(ac.destination);osc.start();osc.stop(ac.currentTime+.12);osc.onended=()=>ac.close();}catch{}if('Notification' in window&&Notification.permission==='granted'){const notification=new Notification('Puffy · Yeni başvuru',{body:label(key)+' · +'+n,tag:'puffy-approval-'+key});notification.onclick=()=>{window.focus();location.hash=path(key).slice(1);notification.close();};}renderEvents();}
 function paint(){if(!ctx)return;let total=0;for(const [k,n]of Object.entries(counts)){if(!allowed(k))continue;total+=Number(n)||0;document.querySelectorAll(`[data-count="${k}"]`).forEach(x=>{x.textContent=fmt(n);x.classList.toggle('sifir',!n);});const old=$('#r-'+k);if(old){old.textContent=fmt(n);old.classList.toggle('sifir',!n);}}document.title=(total?'('+total+') ':'')+'Puffy Yönetim';$('#approval-total').textContent=fmt(total);$('#approval-bell').setAttribute('aria-label',total+' karar bekliyor · Bildirimler');renderPending();}
 function renderPending(root=$('#pending-content')){if(!ctx||!root)return;root.innerHTML=[...['short','sikayet'],...Object.keys(defs)].filter(allowed).map(k=>`<a class="queue-row queue-link" href="${path(k)}"><span>${ctx.esc(label(k))}<small>İncele →</small></span><b data-count="${k}" class="${counts[k]?'count-hot':''}">${counts[k]===undefined?'—':fmt(counts[k])}</b></a>`).join('')+'<p class="note" id="approval-refresh-note">Sayaçlar açık sekmede 60 saniyede, arka planda 5 dakikada yenilenir.</p>';}
 function visibility(){clearTimeout(timer);if(!document.hidden)poll();else timer=setTimeout(poll,300000);}
 async function poll(){if(!ctx||polling)return;polling=true;const c=ctx,token=epoch;let next={...counts},fail=false;try{const tasks=[];if(c.caps.moderator)tasks.push(c.rpc('yonetim_moderasyon_sayac').then(d=>{next.sikayet=Number(d.sikayet)||0;}));if(c.caps.admin)tasks.push(c.rpc('onay_bekleyenler').then(d=>{if(d)for(const k of Object.keys(d))if(k!=='hesaplandi'&&allowed(k))next[k]=Number(d[k])||0;}));tasks.push(c.rpc('yonetim_onay_ek_sayac').then(d=>{for(const [k,n]of Object.entries(d||{}))if(allowed(k))next[k]=Number(n)||0;}));for(const [k,d]of Object.entries(defs))if(allowed(k)&&!d.paged&&(!c.caps.admin||['call_host','call_host_foto'].includes(k)))tasks.push(c.rpc(d.rpc,d.args||{}).then(v=>{next[k]=rowsOf(v).length;}));const r=await Promise.allSettled(tasks);fail=r.some(x=>x.status==='rejected');if(token!==epoch||ctx!==c)return;try{let more=true;for(let i=0;i<5&&more;i++){const batch=await c.rpc('yonetim_basvuru_olaylari_getir',{p_after:eventCursor});if(token!==epoch||ctx!==c)return;for(const [key,n]of Object.entries(window.PuffyGuvenilirlik.eventCounts(batch.rows)))if(allowed(key))signal(key,n);eventCursor=batch.cursor;more=batch.more;}}catch{fail=true;}counts=next;base=true;paint();$('#approval-bell').classList.toggle('offline',fail);$('#approval-bell').title=fail?'Bazı sayaçlar güncellenemedi; son başarılı değerler korunuyor.':'Sayaçlar güncel';}finally{if(token===epoch){polling=false;clearTimeout(timer);timer=setTimeout(poll,document.hidden?300000:60000);}}}
 async function fetchRows(k){const d=defs[k];if(['ajans_kurma','ajans_logo','etkinlik','bayi_yukleme','call_host','oda_temasi'].includes(k)){try{const v=await ctx.rpc(k==='oda_temasi'?'yonetim_oda_temasi_bekleyenler':'yonetim_onay_kuyrugu_v2',k==='oda_temasi'?{p_limit:25,p_offset:page*25}:{p_tur:k,p_limit:25,p_offset:page*25});return {rows:rowsOf(v),total:v.total,serverPaged:true};}catch(e){if(e.code!=='PGRST202'&&!String(e.message).includes('Could not find the function'))throw e;}}const r=await ctx.rpc(d.rpc,d.paged?{p_limit:25,p_offset:page*25}:d.args||{});return {rows:rowsOf(r).sort((a,b)=>new Date(a.created_at||a.updated_at)-new Date(b.created_at||b.updated_at)),total:d.paged?r.total:rowsOf(r).length,limited:!!d.args?.p_limit&&rowsOf(r).length>=d.args.p_limit};}
 function route(hash){if(!hash.startsWith('onay/'))return false;const k=hash.split('/')[1];if(!defs[k]||!allowed(k)){ctx?.toast('Bu onay ekranı için yetkin yok.');location.hash='ozet';return true;}openKey=k;page=0;document.querySelectorAll('dialog').forEach(d=>d.close());document.querySelectorAll('.workspace > [id^="s-"]').forEach(e=>e.classList.toggle('hidden',e.id!=='s-onay'));document.querySelectorAll('nav a.menu').forEach(a=>a.classList.toggle('aktif',a.getAttribute('href')==='#'+hash));$('#route-name').textContent=defs[k].label;$('#uyg nav').classList.remove('open');load();return true;}
 async function load(){const token=++epoch,c=ctx,k=openKey,root=$('#s-onay');clearTimeout(timer);polling=false;root.innerHTML=`<div class="page-title"><div><div class="eyebrow">Karar merkezi</div><h1>${c.esc(defs[k].label)}</h1><p>En eski başvuru önce. Detayları kontrol et, kararını kaydet.</p></div><div><button id="approval-history">Karar geçmişi</button><button id="approval-reload">Yenile</button></div></div><section class="panel" id="approval-list"><div class="skeleton"></div></section>`;$('#approval-reload').onclick=load;$('#approval-history').onclick=()=>history(k);try{const d=await fetchRows(k);if(token!==epoch||ctx!==c||location.hash!=='#onay/'+k)return;lastRows=d.rows;const rows=defs[k].paged||d.serverPaged?d.rows:d.rows.slice(page*25,(page+1)*25);$('#approval-list').innerHTML=(d.limited?'<div class="alert">Liste sunucunun tek sorgu sınırına ulaştı. Görünen kayıtlar arasında en eski önce; tüm kuyruk için sayfalı sunucu bağlantısı gerekir.</div>':'')+rows.map((r,i)=>`<button class="approval-row" data-review="${i}"><span><strong>${c.esc(nameOf(r))}</strong><small>${c.esc(c.date(r.created_at||r.updated_at))} · ${c.esc(r.applicant_display_id||r.display_id||r.room_display_id||r.id||r.user_id)}</small></span><span>Detay →</span></button>`).join('')+(rows.length?'':'<div class="empty-state">Bekleyen başvuru yok.</div>')+`<div class="pager"><span>${fmt(d.total)} kayıt</span><button id="approval-prev" ${!page?'disabled':''}>Önceki</button><button id="approval-next" ${(page+1)*25>=d.total?'disabled':''}>Sonraki</button></div>`;$('#approval-prev').onclick=()=>{page--;load();};$('#approval-next').onclick=()=>{page++;load();};root.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>detail(k,rows[Number(b.dataset.review)]));}catch(e){if(token!==epoch||ctx!==c||location.hash!=='#onay/'+k)return;$('#approval-list').innerHTML=`<div class="empty-state"><strong>Liste alınamadı</strong><p>${c.esc(c.errorText(e))}</p><button id="approval-retry">Tekrar dene</button></div>`;$('#approval-retry').onclick=load;}finally{if(token===epoch)timer=setTimeout(poll,60000);}}
 async function detail(k,r){const c=ctx,dlg=document.createElement('dialog');dlg.className='approval-dialog';let busy=false;const fields={
 ajans_kurma:{Ad:r.name,WhatsApp:r.contact,Açıklama:r.description,Başvuran:r.applicant_nickname,'Başvuran ID':r.applicant_display_id,Ülke:r.applicant_country,Bölge:r.region_name,'Davet eden':r.inviter_nickname,'Davet eden ID':r.inviter_display_id},
 ajans_logo:{Ajans:r.agency_name,'Ajans ID':r.agency_display_id,'Talep eden':r.requester_nickname},
 etkinlik:{Başlık:r.title,Açıklama:r.description,Oda:r.room_name,'Oda ID':r.room_display_id,Sahibi:r.owner_nickname,Başlangıç:c.date(r.starts_at),Bitiş:c.date(r.ends_at)},
 bayi_yukleme:{Bayi:r.dealer?.nickname,'Tutar · TRY':r.amount_try,'Mevcut stok':r.dealer_balance},
 para_cekme:{Kullanıcı:r.nickname,'Tutar · USD':r.amount_usd,'Net · TRY':r.amount_try_net,'IBAN · son dört':r.iban_masked},
 hesap_silme:{Kullanıcı:r.nickname,'ID':r.display_id,'Talep tarihi':c.date(r.deletion_requested_at),'Anonimleştirme':c.date(new Date(new Date(r.deletion_requested_at).getTime()+14*86400000))},
 ozel_id:{Kullanıcı:r.nickname,'İstenen ID':r.vanity_id,Tür:r.vanity_type},
 oda_kapagi:{Oda:r.room_name,'Oda ID':r.room_display_id},oda_temasi:{Oda:r.room_name,'Oda ID':r.room_display_id,Yükleyen:r.uploader_nickname,'Coin':r.price,'Kiralama · gün':r.days},
 call_host:{Kullanıcı:r.nickname,'ID':r.display_id,'Sesli':r.sesli?'Evet':'Hayır','Görüntülü':r.goruntulu?'Evet':'Hayır',Not:r.not},call_host_foto:{Kullanıcı:r.nickname,'ID':r.display_id}
 }[k];let media='';if(k==='ajans_logo')media=safeImage(r.current_avatar_url,'Mevcut logo')+safeImage(r.avatar_url,'Yeni logo');else if(k==='call_host_foto')media=safeImage(r.foto_url,'Mevcut fotoğraf')+safeImage(r.bekleyen_foto_url,'Bekleyen fotoğraf');else media=safeImage(r.avatar_url||r.cover_url||r.foto_url||r.requested_url,'Başvuru görseli',r.media_type);
 dlg.innerHTML=`<form><div class="eyebrow">${c.esc(defs[k].label)}</div><h2>${c.esc(nameOf(r))}</h2>${pairs(fields)}<div class="approval-media">${media}</div>${r.inviter_proof_path?'<div id="proof-slot">Kanıt görseli yükleniyor…</div>':''}${k==='ajans_kurma'?'<label>Ajans kodu · isteğe bağlı<input name="code" maxlength="12" pattern="[A-Za-z0-9]{3,12}" placeholder="Boşsa sunucu adından üretir"></label>':''}${k==='para_cekme'&&c.caps.actions?.withdrawal_bank===true?'<button type="button" data-bank>Banka bilgisini karar için göster</button><div id="bank-slot"></div>':''}${k==='bayi_yukleme'?'<label>Verilecek coin<input name="amount" type="number" min="1" step="1" required></label><p id="dealer-quote" class="note">Güncel teklif hesaplanıyor…</p>':''}<button type="button" data-case>İş dosyası / sorumluluk / hedef tarih</button><label>Karar<select name="approve"><option value="true">Onayla</option><option value="false">Reddet</option></select></label><label>Sebep / yönetici notu<textarea name="reason" required minlength="3" maxlength="200"></textarea></label><p class="note">Onayladığında işlem sunucuda uygulanır.${k==='hesap_silme'?' Onay mevcut 14 günlük süreyi korur; red silme talebini kaldırır.':''}${k==='para_cekme'?' Onay, bakiyeyi düşürür; banka transferi yaptığını varsaymaz.':''}</p><div class="dialog-error" role="alert"></div><div class="dialog-actions"><button type="button" data-cancel>Vazgeç</button><button type="submit" class="primary">Kararı kaydet</button></div></form>`;dlg.querySelector('form').addEventListener('submit',e=>e.preventDefault());if(k==='bayi_yukleme'){dlg.querySelector('button[type=submit]').disabled=true;dlg.querySelector('[name=approve]').onchange=e=>{const amount=dlg.querySelector('[name=amount]');amount.required=e.target.value==='true';amount.disabled=e.target.value==='false';};}document.body.append(dlg);dlg.querySelectorAll('video').forEach(v=>v.addEventListener('error',()=>{dlg.dataset.mediaError='true';const p=document.createElement('p');p.setAttribute('role','alert');p.textContent='Video oynatılamadı. İzlenemeyen içerik onaylanamaz.';v.after(p);}));dlg.showModal();dlg.addEventListener('close',()=>dlg.remove());dlg.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dlg.querySelector('[data-cancel]').onclick=()=>dlg.close();
 dlg.querySelector('[data-case]').onclick=async()=>{const id=k==='call_host_foto'||k==='hesap_silme'?r.user_id:k==='oda_kapagi'?r.job_id:r.id;try{const data=await c.rpc('yonetim_onay_dosyasi',{p_tur:k,p_id:id});if(ctx!==c||!dlg.open)return;const box=document.createElement('dialog');box.innerHTML='<form><h2>İş dosyası</h2><pre>'+c.esc(JSON.stringify(data,null,2))+'</pre><label>Hedef tarih<input name="due" type="datetime-local"></label><label>Not<textarea name="note" maxlength="1000"></textarea></label><p role="alert"></p><button type="button">Kapat</button><button>İşi üstlen ve kaydet</button></form>';document.body.append(box);box.showModal();box.onclose=()=>box.remove();box.querySelector('[type=button]').onclick=()=>box.close();box.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await c.rpc('yonetim_onay_ata',{p_tur:k,p_id:id,p_son_tarih:f.get('due')?new Date(String(f.get('due'))).toISOString():null,p_not:String(f.get('note')||'')});box.close();c.toast('İş sorumluluğu kaydedildi.');}catch(e){box.querySelector('[role=alert]').textContent=c.errorText(e);}};}catch(e){c.toast(c.errorText(e));}};
 if(k==='para_cekme'&&c.caps.actions?.withdrawal_bank===true)dlg.querySelector('[data-bank]').onclick=async()=>{try{const bank=await c.rpc('yonetim_para_cekme_karar_detayi',{p_id:r.id});if(dlg.isConnected)dlg.querySelector('#bank-slot').innerHTML=(bank.kimlik_var?'':'<p class="danger-note">Bu talepte TC/adres bilgisi yok; onaylanamaz. Reddedip kullanıcıdan ödeme bilgileriyle yeniden talep isteyin.</p>')+pairs({'Ad soyad':bank.holder,'TC kimlik no':bank.tc||'—','Adres':bank.adres||'—','IBAN':bank.iban,['TCMB kuru · '+(bank.tcmb_kur_tarihi||'')]:Number(bank.tcmb_kur).toLocaleString('tr-TR',{minimumFractionDigits:4}),'Brüt · TL':Number(bank.brut_tl).toLocaleString('tr-TR',{minimumFractionDigits:2}),['Stopaj %'+Math.round(Number(bank.stopaj_orani)*100)+' · TL']:Number(bank.stopaj_tl).toLocaleString('tr-TR',{minimumFractionDigits:2}),'Gönderilecek net · TL':Number(bank.net_tl).toLocaleString('tr-TR',{minimumFractionDigits:2})})+'<p class="note">Tutarlar bugünkü TCMB kuruyla; onayladığın anda kesinleşir ve gider pusulası seri numarasıyla oluşur (Muhasebe sayfası).</p>';}catch(e){if(dlg.isConnected)dlg.querySelector('#bank-slot').textContent=c.errorText(e);}};
 if(r.inviter_proof_path)c.sb.storage.from('agency-proofs').createSignedUrl(r.inviter_proof_path,300).then(({data,error})=>{if(dlg.isConnected)dlg.querySelector('#proof-slot').innerHTML=error?'<p>Kanıt görseli açılamadı. Yeniden kontrol etmeden karar verme.</p>':safeImage(data.signedUrl,'Davet kanıtı');}).catch(()=>{if(dlg.isConnected)dlg.querySelector('#proof-slot').textContent='Kanıt görseli alınamadı.';});
 if(k==='oda_temasi'&&r.image){/* Tema resimleri 'room-themes' kovasında; yol kova adıyla başlıyor (2026-10-03). */const u=/^https?:\/\//i.test(r.image)?r.image:c.sb.storage.from('room-themes').getPublicUrl(String(r.image).replace(/^room-themes\//,'')).data.publicUrl;dlg.querySelector('.approval-media').innerHTML=safeImage(u,'Oda teması');}
 if(k==='bayi_yukleme')try{const q=await c.rpc('platform_bayi_teklif_hesapla',{p_tutar:r.amount_try,p_para_birimi:'TRY'});if(dlg.isConnected){dlg.querySelector('[name=amount]').value=q.toplam_coin;dlg.querySelector('#dealer-quote').textContent=`Taban ${fmt(q.taban_coin)} + %${q.bonus_yuzde} bonus ${fmt(q.bonus_coin)} = ${fmt(q.toplam_coin)} coin`;}}catch(e){if(dlg.isConnected)dlg.querySelector('#dealer-quote').textContent=c.errorText(e);}
 if(k==='bayi_yukleme'&&dlg.isConnected)dlg.querySelector('button[type=submit]').disabled=false;
 dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.target),approve=f.get('approve')==='true',reason=String(f.get('reason')).trim();if(reason.length<3)return;if(approve&&dlg.dataset.mediaError){c.toast('Video oynatılamadı; onay engellendi.');return;}busy=true;dlg.querySelectorAll('button').forEach(b=>b.disabled=true);try{let out;
 if(k==='hesap_silme')out=await c.rpc('yonetim_hesap_silme_karar',{p_user:r.user_id,p_talep_at:r.deletion_requested_at,p_karar:approve?'onay':'reddet',p_neden:reason});
 else {const amount=Number(f.get('amount'));if(k==='bayi_yukleme'&&approve&&(!Number.isSafeInteger(amount)||amount<1))throw new Error('INVALID_AMOUNT');out=await c.rpc('yonetim_onay_karari',{p_tur:k,p_id:k==='call_host_foto'?r.user_id:k==='oda_kapagi'?r.job_id:r.id,p_onay:approve,p_neden:reason,p_coin:k==='bayi_yukleme'&&approve?amount:null,p_kod:k==='ajans_kurma'?(f.get('code')||null):null});}
 if(ctx!==c||!dlg.isConnected)return;
 if(out?.error||out?.ok===false)throw new Error(out.error||'OPERATION_REJECTED');dlg.close();c.toast('Karar kaydedildi.');await load();await poll();}catch(ex){if(dlg.isConnected){dlg.querySelector('.dialog-error').textContent=c.errorText(ex);busy=false;dlg.querySelectorAll('button').forEach(b=>b.disabled=false);}}};
 }
 async function history(k){const c=ctx,dlg=document.createElement('dialog');dlg.className='phase2-dialog';document.body.append(dlg);dlg.showModal();dlg.onclose=()=>dlg.remove();let offset=0;async function render(){try{const d=await c.rpc('yonetim_karar_gecmisi',{p_tur:k,p_limit:25,p_offset:offset});if(ctx!==c||!dlg.open)return;dlg.innerHTML='<h2>Karar geçmişi</h2>'+d.rows.map(x=>`<article><p>${c.esc(c.date(x.created_at))} · Aktör ${c.esc(x.yonetici_id)}</p>${x.hedef_id?`<a href="#kullanici/${c.esc(x.hedef_id)}">Hedef kullanıcı</a>`:''}<pre>${c.esc(JSON.stringify(x.ayrinti,null,2))}</pre></article>`).join('')+`<p>${c.esc(d.total)} karar. Tarihsel kayıtlarda yalnız o tarihte tutulan kanıtlar bulunur.</p><button data-prev ${offset?'':'disabled'}>Önceki</button><button data-next ${offset+25>=d.total?'disabled':''}>Sonraki</button><button data-close>Kapat</button>`;dlg.querySelector('[data-prev]').onclick=()=>{offset-=25;render();};dlg.querySelector('[data-next]').onclick=()=>{offset+=25;render();};dlg.querySelector('[data-close]').onclick=()=>dlg.close();}catch(e){if(dlg.open){dlg.innerHTML='<p role="alert">'+c.esc(c.errorText(e))+'</p><button>Kapat</button>';dlg.querySelector('button').onclick=()=>dlg.close();}}}render();}
 async function liveRooms(offset=0){if(!ctx?.caps.admin){location.hash='ozet';return;}const c=ctx,root=$('#s-onay');document.querySelectorAll('.workspace > [id^="s-"]').forEach(e=>e.classList.toggle('hidden',e.id!=='s-onay'));$('#route-name').textContent='Canlı odalar';root.innerHTML='<h1>Canlı odalar</h1><div class="skeleton"></div>';try{const d=await c.rpc('yonetim_canli_odalar',{p_limit:100,p_offset:offset});if(location.hash!=='#canli-odalar'||ctx!==c)return;root.innerHTML='<h1>Canlı odalar</h1><p class="note">Son 150 saniyede varlık sinyali gönderen odalar.</p>'+d.rows.map(r=>`<a class="queue-row queue-link" href="#kullanici/${c.esc(r.owner_id)}"><span>${c.esc(r.name)} · ${c.esc(r.display_id)}</span><span>Sahibi →</span></a>`).join('')+(d.rows.length?'':'<p>Şu anda canlı oda yok.</p>')+`<div class="pager"><span>${fmt(d.total)} oda</span><button data-prev ${offset?'':'disabled'}>Önceki</button><button data-next ${offset+100>=d.total?'disabled':''}>Sonraki</button></div>`;root.querySelector('[data-prev]').onclick=()=>liveRooms(Math.max(0,offset-100));root.querySelector('[data-next]').onclick=()=>liveRooms(offset+100);}catch(e){if(location.hash==='#canli-odalar'&&ctx===c){root.innerHTML='<h1>Canlı odalar</h1><p>'+c.esc(c.errorText(e))+'</p><button data-retry>Tekrar dene</button>';root.querySelector('[data-retry]').onclick=()=>liveRooms(offset);}}}
 window.PuffyApprovals={init,stop,route,poll,renderPending,defs,liveRooms};
})();
