/* Ayarlar (platform sahibi) ve Duyuru (süper yönetici + sahip). Tüm veriler MFA kapılı RPC'lerden. */
(() => {
 'use strict';
 let ctx=null,seq=0;
 const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('tr-TR').format(n??0);
 const esc=x=>ctx.esc(x);
 const PLATFORM=[
  {grup:'Kurlar ve ekonomi',alanlar:[
   ['usd_to_coin_rate','1 $ kaç coin','Uygulama içi mağaza ve bayi kuru. Örn. 18000.','number'],
   ['usd_to_try_rate','1 $ kaç ₺','Bayi havalesi ve ödemelerde kullanılan kur.','number'],
   ['dealer_wholesale_coin_per_usd','Bayi toptan kuru (1 $ kaç coin)','Boş/0 ise mağaza kuru kullanılır.','number'],
   ['cevirme_bonus_oran','Kendi kazancını coine çevirme bonusu','0 = bire bir (1 $ = 18.000 coin). 0.20 = %20.','number'],
   ['bayiye_aktarim_bonus_oran','Kazancı bayiye aktarma bonusu','Bayinin stoğuna eklenen fazla. 0.20 = %20 (100 $ → 2.160.000 coin).','number'],
   ['minimum_withdrawal_usd','En düşük para çekme ($)','','number'],
   ['stopaj_rate','Stopaj oranı','0.20 = %20','number'],
   ['agency_exit_fee_rate','Ajanstan çıkış bedeli oranı','0.10 = %10','number'],
   ['refund_deduction_rate','İade kesinti oranı','0.10 = %10','number'],
   ['agency_reward_min_coins','Ajans ödülü için en az coin','','number'],
   ['diamond_reminder_threshold','Elmas hatırlatma eşiği','','number'],
   ['min_vip_level_for_owner_bonus','Oda sahibi bonusu için en düşük VIP','','number']]},
  {grup:'Uygulama ve destek',alanlar:[
   ['min_app_version','Zorunlu en düşük sürüm','Örn. 1.0.0+21. Altındaki sürümler güncelleme ister.','text'],
   ['update_url','Güncelleme bağlantısı','https:// ile başlamalı.','text'],
   ['support_email','Destek e-postası','','text'],
   ['support_whatsapp','Destek WhatsApp','','text'],
   ['support_faq_url','SSS bağlantısı','https:// ile başlamalı.','text'],
   ['support_room_id','Destek odası ID','','text']]}];
 const ARAMA=[['yayinci_dk_coin','Görüntülü dakika (coin)'],['yayinci_sesli_dk_coin','Sesli dakika (coin)'],['dip_dk_coin','Call host olmayan görüntülü dakika (coin)'],['dip_sesli_dk_coin','Call host olmayan sesli dakika (coin)'],['yayinci_pay','Yayıncı payı (0.30 = %30)'],['ajans_pay','Ajans payı (0.10 = %10)'],['ucretsiz_sn','Ücretsiz saniye'],['min_dolar_puffy','Dolar talebi için en az Puffy'],['puffy_usd_1000','1.000 Puffy kaç $']];
 const HEDEF={herkes:'Herkes',vip:'VIP üyeler',ajans_sahipleri:'Ajans sahipleri',call_host:'Call Host\'lar',bayiler:'Bayiler'};
 function mount(id,title){const root=$('#s-ayarlar');document.querySelectorAll('.workspace > [id^="s-"]').forEach(e=>e.classList.toggle('hidden',e!==root));document.querySelectorAll('nav a.menu').forEach(a=>a.classList.toggle('aktif',a.dataset.sayfa===id));$('#uyg nav').classList.remove('open');$('#panel-topbar .mobile-menu')?.setAttribute('aria-expanded','false');$('#route-name').textContent=title;return root;}
 function init(c){stop();ctx=c;const host=$('#ayar-nav');host.innerHTML=(c.caps.owner||c.caps.super?'<a class="menu" href="#duyuru" data-sayfa="duyuru"><span>Duyuru gönder</span></a>':'')+(c.caps.owner?'<a class="menu" href="#muhasebe" data-sayfa="muhasebe"><span>Muhasebe</span></a><a class="menu" href="#ayarlar" data-sayfa="ayarlar"><span>Ayarlar</span></a>':'');}
 function stop(){seq++;ctx=null;$('#ayar-nav')?.replaceChildren();$('#s-ayarlar')?.replaceChildren();}
 function sebepDialog(title,body,onSubmit,submitLabel='Kaydet'){const dlg=document.createElement('dialog');dlg.className='phase2-dialog';dlg.setAttribute('aria-label',title);
  dlg.innerHTML=`<form><div class="eyebrow">AYARLAR</div><h2>${esc(title)}</h2>${body||''}<label>Değişiklik sebebi<textarea name="reason" required minlength="3" maxlength="300"></textarea></label><p class="danger-note">Onayladığında değişiklik anında uygulanır ve kütüğe yazılır.</p><div class="dialog-error" role="alert"></div><div class="dialog-actions"><button type="button" data-cancel>Vazgeç</button><button type="submit" class="primary">${esc(submitLabel)}</button></div></form>`;
  document.body.append(dlg);dlg.showModal();dlg.addEventListener('close',()=>dlg.remove());dlg.querySelector('[data-cancel]').onclick=()=>dlg.close();let busy=false;
  dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.target),reason=String(f.get('reason')||'').trim(),err=dlg.querySelector('.dialog-error');if(reason.length<3){err.textContent='Sebebi yaz.';return;}busy=true;dlg.querySelectorAll('button').forEach(b=>b.disabled=true);err.textContent='';
   try{await onSubmit(reason,f);dlg.close();}catch(ex){err.textContent=ctx?.errorText(ex)||String(ex.message);busy=false;dlg.querySelectorAll('button').forEach(b=>b.disabled=false);}};return dlg;}
 async function kaydet(tur,veri,reason){const out=await ctx.rpc('yonetim_ayar_kaydet',{p_tur:tur,p_veri:veri,p_neden:reason});if(out?.ok===false)throw new Error(out.error||'OPERATION_REJECTED');ctx.toast('Kaydedildi.');}
 const val=(d,key)=>{const v=d.platform?.[key]?.value;return v==null?'':typeof v==='object'?JSON.stringify(v):String(v);};
 function platformHtml(d){return PLATFORM.map(g=>`<section class="panel"><h3>${esc(g.grup)}</h3>${g.alanlar.map(([k,l,n,t])=>`<form class="ayar-row" data-key="${k}" data-type="${t}"><label>${esc(l)}<input name="v" type="${t==='number'?'number':'text'}" ${t==='number'?'step="any" min="0"':'maxlength="300"'} value="${esc(val(d,k))}"></label>${n?`<small>${esc(n)}</small>`:''}<span class="ayar-meta">${d.platform?.[k]?'Son: '+esc(ctx.date(d.platform[k].updated_at)):'Kayıt yok'}</span><button class="primary">Kaydet</button></form>`).join('')}</section>`).join('');}
 function oyunHtml(d){const o=d.platform?.oyun_ayarlari?.value||{};const test=Array.isArray(o.test_kullanicilari)?o.test_kullanicilari:[];return `<section class="panel"><h3>Oyunlar</h3><form class="ayar-row" data-oyun><label>Anka Hazinesi<select name="acik"><option value="false" ${o.anka_hazinesi?'':'selected'}>Kapalı (yalnız test hesapları)</option><option value="true" ${o.anka_hazinesi?'selected':''}>Herkese açık</option></select></label><label>Test hesapları (UUID, satır satır)<textarea name="test" rows="3">${esc(test.join('\n'))}</textarea></label><small>Kapalıyken oyun konsolunda görünmez; test hesapları denemeye devam eder. Uygulama güncellemesi gerekmez.</small><button class="primary">Kaydet</button></form></section>`;}
 function aramaHtml(d){const a=d.arama||{};return `<section class="panel"><h3>Ücretli arama</h3><form class="ayar-grid" data-arama>${ARAMA.map(([k,l])=>`<label>${esc(l)}<input name="${k}" type="number" step="any" min="0" value="${esc(a[k]??'')}"></label>`).join('')}<div class="ayar-actions"><small>Son güncelleme: ${esc(ctx.date(a.updated_at))}. Değişiklik yeni aramalarda geçerli olur.</small><button class="primary">Tümünü kaydet</button></div></form></section>`;}
 function bayiHtml(d){const rows=d.bayi_kademeleri||[];return `<section class="panel"><h3>Bayi bonus kademeleri</h3><p class="note">Yükleme tutarı (USD) bu eşiğe ulaşınca bonus yüzdesi uygulanır. Tutarlar ₺'ye 1 $ = ${esc(d.try_kur)} ₺ kuruyla çevrilir. En az 1, en çok 8 kademe.</p><form data-bayi><table class="data-table"><thead><tr><th>Eşik ($)</th><th>Bonus %</th><th></th></tr></thead><tbody>${rows.map(r=>bayiRow(r.min_usd,r.yuzde)).join('')||bayiRow(0,10)}</tbody></table><div class="ayar-actions"><button type="button" data-add>Kademe ekle</button><button class="primary">Kademeleri kaydet</button></div></form></section>`;}
 const bayiRow=(m,p)=>`<tr><td><input name="min_usd" type="number" min="0" step="1" value="${esc(m)}" required></td><td><input name="yuzde" type="number" min="0" max="100" step="0.5" value="${esc(p)}" required></td><td><button type="button" data-del aria-label="Sil">×</button></td></tr>`;
 function maasHtml(d){const rows=d.kademe_maas||[];return `<section class="panel"><h3>Kademe maaş tablosu (yarım aylık)</h3><p class="note">Hedef: dönemde alınan hediyelerin coin değeri. Maaşlar dolar. Satırı değiştirip "Kaydet"e bas.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Kademe</th><th>Hedef (coin)</th><th>Yayıncı $</th><th>Ajans sahibi $</th><th>Çıkış bedeli (coin)</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.level)}</strong></td><td><input name="target_coins" type="number" min="0" step="1" value="${esc(r.target_coins)}"></td><td><input name="host_salary_usd" type="number" min="0" step="0.01" value="${esc(r.host_salary_usd)}"></td><td><input name="owner_salary_usd" type="number" min="0" step="0.01" value="${esc(r.owner_salary_usd)}"></td><td><input name="exit_fee_coins" type="number" min="0" step="1" value="${esc(r.exit_fee_coins)}"></td><td><button type="button" data-maas="${esc(r.level)}">Kaydet</button></td></tr>`).join('')}</tbody></table></div></section>`;}
 function gecmisHtml(d){const rows=d.gecmis||[];return `<section class="panel"><h3>Son değişiklikler</h3>${rows.length?`<div class="table-wrap"><table class="data-table responsive"><thead><tr><th>Tarih</th><th>Ayar</th><th>Eski</th><th>Yeni</th><th>Sebep</th><th>Kim</th></tr></thead><tbody>${rows.map(r=>`<tr><td data-label="Tarih">${esc(ctx.date(r.at))}</td><td data-label="Ayar">${esc(r.key)}</td><td data-label="Eski"><code>${esc(kisa(r.old))}</code></td><td data-label="Yeni"><code>${esc(kisa(r.new))}</code></td><td data-label="Sebep">${esc(r.reason||'—')}</td><td data-label="Kim">${esc(r.by||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty-state">Henüz değişiklik yok.</p>'}</section>`;}
 const kisa=v=>{const s=v==null?'—':typeof v==='object'?JSON.stringify(v):String(v);return s.length>60?s.slice(0,57)+'…':s;};
 async function ayarlar(){if(!ctx?.caps.owner){location.hash='ozet';return;}const c=ctx,n=++seq,root=mount('ayarlar','Ayarlar');root.innerHTML='<div class="skeleton" role="status" aria-label="Yükleniyor"></div>';
  try{const d=await c.rpc('yonetim_ayarlar_getir');if(ctx!==c||n!==seq)return;
   root.innerHTML=`<div class="page-title"><div><div class="eyebrow">PLATFORM SAHİBİ</div><h1>Ayarlar</h1><p>Kurlar, sürüm, oyunlar, arama ücretleri, bayi ve kademe tabloları. Her kayıt sebep ister ve kütüğe yazılır.</p></div><button data-refresh>Yenile</button></div>${platformHtml(d)}${oyunHtml(d)}${aramaHtml(d)}${bayiHtml(d)}${maasHtml(d)}${gecmisHtml(d)}<p class="note">Veri zamanı: ${esc(c.date(d.as_of))}.</p>`;
   root.querySelector('[data-refresh]').onclick=()=>ayarlar();
   root.querySelectorAll('form.ayar-row[data-key]').forEach(f=>f.onsubmit=e=>{e.preventDefault();const key=f.dataset.key,raw=f.querySelector('[name=v]').value.trim();let value;if(f.dataset.type==='number'){if(raw===''||!Number.isFinite(Number(raw))){c.toast('Sayı gir.');return;}value=Number(raw);}else value=raw;sebepDialog(f.querySelector('label').firstChild.textContent.trim(),`<p>Yeni değer: <code>${esc(String(value))}</code></p>`,async reason=>{await kaydet('platform',{key,value},reason);ayarlar();});});
   root.querySelector('form[data-oyun]').onsubmit=e=>{e.preventDefault();const f=e.target;const acik=f.querySelector('[name=acik]').value==='true';const test=f.querySelector('[name=test]').value.split(/\s+/).map(x=>x.trim()).filter(Boolean);if(test.some(x=>!/^[0-9a-f-]{36}$/i.test(x))){c.toast('Test hesapları UUID olmalı.');return;}sebepDialog('Anka Hazinesi',`<p>${acik?'Oyun herkese AÇILACAK.':'Oyun KAPATILACAK (yalnız test hesapları).'}</p>`,async reason=>{await kaydet('platform',{key:'oyun_ayarlari',value:{anka_hazinesi:acik,test_kullanicilari:test}},reason);ayarlar();});};
   root.querySelector('form[data-arama]').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),veri={};for(const [k] of ARAMA){const raw=String(f.get(k)||'').trim();if(raw==='')continue;if(!Number.isFinite(Number(raw))){c.toast('Sayı gir: '+k);return;}veri[k]=Number(raw);}sebepDialog('Ücretli arama ayarları',`<p>${Object.entries(veri).map(([k,v])=>`${esc(k)}: <code>${esc(v)}</code>`).join('<br>')}</p>`,async reason=>{await kaydet('arama',veri,reason);ayarlar();});};
   const bayiForm=root.querySelector('form[data-bayi]');bayiForm.querySelector('[data-add]').onclick=()=>{if(bayiForm.querySelectorAll('tbody tr').length>=8){c.toast('En çok 8 kademe.');return;}bayiForm.querySelector('tbody').insertAdjacentHTML('beforeend',bayiRow('',''));};bayiForm.addEventListener('click',e=>{if(e.target.matches('[data-del]')){if(bayiForm.querySelectorAll('tbody tr').length<=1){c.toast('En az 1 kademe kalmalı.');return;}e.target.closest('tr').remove();}});
   bayiForm.onsubmit=e=>{e.preventDefault();const rows=[...bayiForm.querySelectorAll('tbody tr')].map(tr=>({min_usd:Number(tr.querySelector('[name=min_usd]').value),yuzde:Number(tr.querySelector('[name=yuzde]').value)})).sort((a,b)=>a.min_usd-b.min_usd);if(rows.some(r=>!Number.isFinite(r.min_usd)||!Number.isFinite(r.yuzde))){c.toast('Tüm alanları doldur.');return;}if(new Set(rows.map(r=>r.min_usd)).size!==rows.length){c.toast('Aynı eşik iki kez girilemez.');return;}sebepDialog('Bayi kademeleri',`<p>${rows.map(r=>`${fmt(r.min_usd)} $ → %${r.yuzde}`).join('<br>')}</p>`,async reason=>{await kaydet('bayi_kademe',rows,reason);ayarlar();});};
   root.querySelectorAll('[data-maas]').forEach(b=>b.onclick=()=>{const level=Number(b.dataset.maas),tr=b.closest('tr'),veri={level};for(const k of ['target_coins','host_salary_usd','owner_salary_usd','exit_fee_coins']){const v=tr.querySelector(`[name=${k}]`).value.trim();if(v===''||!Number.isFinite(Number(v))){c.toast('Sayı gir.');return;}veri[k]=Number(v);}sebepDialog('Kademe '+level,`<p>Hedef ${fmt(veri.target_coins)} coin · yayıncı $${veri.host_salary_usd} · ajans $${veri.owner_salary_usd} · çıkış ${fmt(veri.exit_fee_coins)} coin</p>`,async reason=>{await kaydet('kademe_maas',veri,reason);ayarlar();});});
  }catch(e){if(ctx===c&&n===seq){root.innerHTML=`<div class="page-title"><h1>Ayarlar</h1></div><div class="empty-state" role="alert"><strong>Veri alınamadı</strong><p>${esc(c.errorText(e))}</p><button data-retry>Tekrar dene</button></div>`;root.querySelector('[data-retry]').onclick=()=>ayarlar();}}}
 async function duyuru(){if(!(ctx?.caps.owner||ctx?.caps.super)){location.hash='ozet';return;}const c=ctx,n=++seq,root=mount('duyuru','Duyuru gönder');root.innerHTML='<div class="skeleton" role="status" aria-label="Yükleniyor"></div>';
  try{const rows=await c.rpc('yonetim_duyurular_liste',{p_limit:30});if(ctx!==c||n!==seq)return;
   root.innerHTML=`<div class="page-title"><div><div class="eyebrow">İLETİŞİM</div><h1>Duyuru gönder</h1><p>Seçtiğin gruba uygulama içi sistem mesajı olarak gider (Mesajlar → Puffy).</p></div><button data-refresh>Yenile</button></div><section class="panel"><form data-duyuru class="ayar-grid"><label>Hedef<select name="hedef">${Object.entries(HEDEF).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('')}</select></label><label>Başlık<input name="baslik" maxlength="80" required></label><label class="wide">Mesaj<textarea name="metin" rows="5" maxlength="1000" required></textarea></label><div class="ayar-actions"><small>Saatte en çok 10 duyuru. Gönderim geri alınamaz.</small><button class="primary">Gönder</button></div></form></section><section class="panel"><h3>Geçmiş duyurular</h3>${rows.length?rows.map(r=>`<article class="content-card"><small>${esc(c.date(r.at))} · ${esc(HEDEF[r.hedef]||r.hedef)} · ${fmt(r.alici)} alıcı · ${esc(r.yazan||'—')}</small><strong>${esc(r.baslik)}</strong><p>${esc(r.metin)}</p></article>`).join(''):'<p class="empty-state">Henüz duyuru gönderilmedi.</p>'}</section>`;
   root.querySelector('[data-refresh]').onclick=()=>duyuru();
   root.querySelector('form[data-duyuru]').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),hedef=String(f.get('hedef')),baslik=String(f.get('baslik')||'').trim(),metin=String(f.get('metin')||'').trim();if(baslik.length<2||metin.length<3){c.toast('Başlık ve mesajı yaz.');return;}const request=crypto.randomUUID();
    sebepDialog('Duyuruyu gönder',`<p><b>${esc(HEDEF[hedef])}</b> grubuna gidecek:</p><p><strong>${esc(baslik)}</strong><br>${esc(metin).replace(/\n/g,'<br>')}</p>`,async()=>{const out=await c.rpc('yonetim_duyuru_gonder',{p_baslik:baslik,p_metin:metin,p_hedef:hedef,p_request_id:request});if(out?.ok===false)throw new Error(out.error||'OPERATION_REJECTED');c.toast(`Gönderildi · ${fmt(out.alici)} alıcı.`);duyuru();},'Gönder');};
  }catch(e){if(ctx===c&&n===seq){root.innerHTML=`<div class="page-title"><h1>Duyuru</h1></div><div class="empty-state" role="alert"><strong>Veri alınamadı</strong><p>${esc(c.errorText(e))}</p><button data-retry>Tekrar dene</button></div>`;root.querySelector('[data-retry]').onclick=()=>duyuru();}}}
 // MUHASEBE (2026-10-04): onaylı para çekmelerin gider pusulaları ve aylık stopaj listesi.
 const tl=n=>new Intl.NumberFormat('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
 const AYLAR=['Ocak','Şubat','Mart','Nisan','Mayıs','Haziran','Temmuz','Ağustos','Eylül','Ekim','Kasım','Aralık'];
 function pusulaHtml(p){const f=p.firma||{},k=p.kisi||{},e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const tarih=new Date(p.tarih).toLocaleDateString('tr-TR');const kurTarih=p.tcmb_kur_tarihi?new Date(p.tcmb_kur_tarihi).toLocaleDateString('tr-TR'):'—';
  return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><title>Gider Pusulası ${e(p.seri_no)}</title><style>body{font-family:Arial,Helvetica,sans-serif;color:#111;margin:32px;font-size:13px}h1{text-align:center;font-size:20px;margin:0 0 4px;letter-spacing:2px}.ust{display:flex;justify-content:space-between;border:1px solid #111;padding:10px 12px;margin:14px 0}.kutu{border:1px solid #111;padding:10px 12px;margin-bottom:14px}.kutu h3{margin:0 0 6px;font-size:13px;text-transform:uppercase}table{width:100%;border-collapse:collapse;margin-top:6px}td,th{border:1px solid #111;padding:6px 8px;text-align:left}td.r,th.r{text-align:right}tr.net td{font-weight:bold;font-size:14px}.imza{display:flex;justify-content:space-between;margin-top:48px}.imza div{width:45%;border-top:1px solid #111;padding-top:6px;text-align:center}.not{font-size:11px;color:#444;margin-top:18px}@media print{button{display:none}body{margin:12mm}}</style></head><body>
  <button onclick="print()" style="float:right;padding:8px 14px">Yazdır / PDF</button><h1>GİDER PUSULASI</h1>
  <div class="ust"><div><b>Seri No:</b> ${e(p.seri_no)}<br><b>Talep No:</b> ${e(p.talep_no)}</div><div style="text-align:right"><b>Düzenleme Tarihi:</b> ${e(tarih)}</div></div>
  <div class="kutu"><h3>Düzenleyen (İşi yaptıran)</h3>${e(f.unvan)}<br>Vergi Dairesi: ${e(f.vergi_dairesi)} · VKN: ${e(f.vergi_no)}<br>${e(f.adres)}</div>
  <div class="kutu"><h3>İşi yapan / Malı satan</h3>Adı Soyadı: <b>${e(k.ad_soyad)}</b><br>T.C. Kimlik No: ${e(k.tc)}<br>Adres: ${e(k.adres)} ${e(k.ilce)} / ${e(k.il)}<br>IBAN: ${e(k.iban)}</div>
  <table><thead><tr><th>Açıklama</th><th class="r">Tutar</th></tr></thead><tbody>
  <tr><td>${e(p.aciklama)} (${e(p.usd)} USD)</td><td class="r"></td></tr>
  <tr><td>TCMB döviz alış kuru (${e(kurTarih)} · bülten ${e(p.tcmb_bulten_no||'—')})</td><td class="r">${Number(p.tcmb_kur).toLocaleString('tr-TR',{minimumFractionDigits:4,maximumFractionDigits:4})} TL</td></tr>
  <tr><td>Brüt tutar</td><td class="r">${tl(p.brut_tl)} TL</td></tr>
  <tr><td>Gelir vergisi stopajı (%${tl(Number(p.stopaj_orani)*100)})</td><td class="r">−${tl(p.stopaj_tl)} TL</td></tr>
  <tr class="net"><td>Ödenen net tutar</td><td class="r">${tl(p.net_tl)} TL</td></tr></tbody></table>
  <div class="imza"><div>Düzenleyen<br>${e(f.unvan)}</div><div>İşi yapan<br>${e(k.ad_soyad)}</div></div>
  <p class="not">Kesilen stopaj, düzenleyen tarafından işi yapan adına muhtasar beyanname ile vergi dairesine beyan edilir ve ödenir.</p></body></html>`;}
 async function pusulaAc(id){const w=window.open('','_blank');if(!w){ctx.toast('Açılır pencereye izin ver.');return;}w.document.write('<p style="font-family:Arial">Yükleniyor…</p>');try{const p=await ctx.rpc('gider_pusulasi',{p_id:id});w.document.open();w.document.write(pusulaHtml(p));w.document.close();}catch(e){w.document.body.textContent='Pusula alınamadı: '+ctx.errorText(e);}}
 function csvIndir(d){const sayi=n=>String((Number(n)||0).toFixed(2)).replace('.',',');const q=s=>'"'+String(s??'').replace(/"/g,'""')+'"';
  const bas=['Seri No','Tarih','Ad Soyad','TC Kimlik No','Adres','USD','TCMB Kuru','Brüt TL','Stopaj %','Stopaj TL','Net TL','IBAN'];
  const satir=d.satirlar.map(r=>[q(r.seri_no),q(r.tarih),q(r.ad_soyad),q("'"+(r.tc||'')),q(r.adres),sayi(r.usd),String(Number(r.tcmb_kur).toFixed(4)).replace('.',','),sayi(r.brut_tl),sayi(Number(r.stopaj_orani)*100),sayi(r.stopaj_tl),sayi(r.net_tl),q(r.iban)].join(';'));
  const t=d.toplam||{};satir.push(['"TOPLAM ('+t.adet+' pusula)"','','','','',sayi(t.usd),'',sayi(t.brut_tl),'',sayi(t.stopaj_tl),sayi(t.net_tl),''].join(';'));
  const ust=[q((d.firma?.unvan||'')+' · VKN '+(d.firma?.vergi_no||'')),q('Stopaj listesi: '+AYLAR[d.ay-1]+' '+d.yil)].join(';');
  const blob=new Blob(['﻿'+[ust,'',bas.map(q).join(';'),...satir].join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`stopaj_${d.yil}_${String(d.ay).padStart(2,'0')}.csv`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),2000);}
 async function muhasebe(){if(!ctx?.caps.owner){location.hash='ozet';return;}const c=ctx,n=++seq,root=mount('muhasebe','Muhasebe');const simdi=new Date();
  root.innerHTML=`<div class="page-title"><div><div class="eyebrow">PLATFORM SAHİBİ</div><h1>Muhasebe · Stopaj</h1><p>Onaylanan para çekmelerin gider pusulaları (seri no sırasıyla) ve muhasebeye verilecek aylık liste.</p></div></div><section class="panel"><form data-donem class="ayar-grid"><label>Yıl<input name="yil" type="number" min="2026" max="2100" value="${simdi.getFullYear()}"></label><label>Ay<select name="ay">${AYLAR.map((a,i)=>`<option value="${i+1}" ${i===simdi.getMonth()?'selected':''}>${a}</option>`).join('')}</select></label><div class="ayar-actions"><button class="primary">Getir</button></div></form></section><div data-sonuc></div>`;
  const form=root.querySelector('form[data-donem]'),out=root.querySelector('[data-sonuc]');
  const getir=async()=>{const f=new FormData(form),yil=Number(f.get('yil')),ay=Number(f.get('ay'));out.innerHTML='<div class="skeleton" role="status" aria-label="Yükleniyor"></div>';
   try{const d=await c.rpc('stopaj_aylik_liste',{p_yil:yil,p_ay:ay});if(ctx!==c||n!==seq)return;const t=d.toplam||{};
    out.innerHTML=`<section class="panel"><div class="page-title"><h3>${esc(AYLAR[ay-1])} ${esc(yil)} · ${esc(fmt(t.adet))} pusula</h3><button data-csv ${t.adet?'':'disabled'}>Excel (CSV) indir</button></div>
    <div class="metrics">${[['Brüt',tl(t.brut_tl)+' TL'],['Stopaj',tl(t.stopaj_tl)+' TL'],['Net ödenen',tl(t.net_tl)+' TL'],['USD',tl(t.usd)+' $']].map(([a,b])=>`<div><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('')}</div>
    ${t.adet?`<div class="table-wrap"><table class="data-table responsive"><thead><tr><th>Seri No</th><th>Tarih</th><th>Ad Soyad</th><th>TC</th><th>Brüt TL</th><th>Stopaj TL</th><th>Net TL</th><th></th></tr></thead><tbody>${d.satirlar.map(r=>`<tr><td data-label="Seri No"><strong>${esc(r.seri_no)}</strong></td><td data-label="Tarih">${esc(r.tarih)}</td><td data-label="Ad Soyad">${esc(r.ad_soyad)}</td><td data-label="TC">${esc(r.tc)}</td><td data-label="Brüt">${esc(tl(r.brut_tl))}</td><td data-label="Stopaj">${esc(tl(r.stopaj_tl))}</td><td data-label="Net">${esc(tl(r.net_tl))}</td><td><button data-pusula="${esc(r.id)}">Pusula</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="empty-state">Bu ay onaylanmış ödeme yok.</p>'}</section>`;
    out.querySelector('[data-csv]').onclick=()=>csvIndir(d);out.querySelectorAll('[data-pusula]').forEach(b=>b.onclick=()=>pusulaAc(b.dataset.pusula));
   }catch(e){if(ctx===c&&n===seq)out.innerHTML=`<div class="empty-state" role="alert"><strong>Veri alınamadı</strong><p>${esc(c.errorText(e))}</p></div>`;}};
  form.onsubmit=e=>{e.preventDefault();getir();};getir();}
 function route(hash){const page=hash.split(/[/?]/)[0];if(page==='muhasebe'){muhasebe();return true;}if(page==='ayarlar'){ayarlar();return true;}if(page==='duyuru'){duyuru();return true;}seq++;return false;}
 window.PuffyAyarlar={init,stop,route};
})();
