/* Bakım modu — 2026-10-09 (D3). Yalnız sahip + MFA (yonetim_bakim_*). Uygulama ≤2 dk içinde algılar. */
(()=>{'use strict';let ctx=null,seq=0;const $=s=>document.querySelector(s);
function init(c){stop();ctx=c;const h=$('#bakim-nav');if(h)h.innerHTML=c.caps.owner?'<a class="menu" href="#bakim" data-sayfa="bakim"><span>Bakım modu</span></a>':'';}
function stop(){seq++;ctx=null;$('#bakim-nav')?.replaceChildren();$('#s-bakim')?.replaceChildren();}
const yerel=d=>{if(!d)return '';const t=new Date(d),p=n=>String(n).padStart(2,'0');return `${t.getFullYear()}-${p(t.getMonth()+1)}-${p(t.getDate())}T${p(t.getHours())}:${p(t.getMinutes())}`;};
async function load(){const c=ctx,n=++seq,root=$('#s-bakim');document.querySelectorAll('.workspace > [id^="s-"]').forEach(e=>e.classList.toggle('hidden',e!==root));const rn=$('#route-name');if(rn)rn.textContent='Bakım modu';root.innerHTML='<div class="skeleton"></div>';
 try{const v=await c.rpc('yonetim_bakim_getir');if(ctx!==c||n!==seq)return;
 root.innerHTML=`<div class="page-title"><div><div class="eyebrow">AYARLAR / BAKIM</div><h1>Bakım modu</h1><p>Açıkken kullanıcılar uygulama yerine bakım ekranı görür (yöneticiler muaf). Uygulama en geç 2 dakikada algılar. Sunucu işlemleri durmaz.</p></div><span class="rozet">${v.aktif?'AÇIK':'kapalı'}</span></div>
 <section class="panel"><form id="bakim-form"><label><input type="checkbox" name="aktif" ${v.aktif?'checked':''}> Bakım modu açık</label><label>Kullanıcı mesajı (en çok 300)<textarea name="mesaj" maxlength="300" rows="3">${c.esc(v.mesaj||'')}</textarea></label><label>Tahmini bitiş (boş = elle kapatılana kadar; geçince otomatik kapanır)<input type="datetime-local" name="bitis" value="${yerel(v.bitis)}"></label><label>İşlem gerekçesi (3–300)<input name="neden" maxlength="300" required></label><p class="hata" id="bakim-hata"></p><button class="primary">Kaydet</button></form></section>`;
 const f=root.querySelector('#bakim-form');f.onsubmit=async e=>{e.preventDefault();const d=new FormData(f),err=root.querySelector('#bakim-hata');const b=String(d.get('bitis')||'');try{f.querySelector('button').disabled=true;await c.rpc('yonetim_bakim_ayarla',{p_aktif:d.has('aktif'),p_mesaj:String(d.get('mesaj')||''),p_bitis:b?new Date(b).toISOString():null,p_neden:String(d.get('neden')||'')});c.toast('Bakım ayarı kaydedildi.');load();}catch(ex){err.textContent=({INVALID_REASON:'Gerekçe 3–300 karakter olmalı.',INVALID_VALUE:'Bitiş zamanı gelecekte olmalı ve mesaj 300 karakteri geçmemeli.'})[ex.message]||(ex.code==='PGRST202'?'Bakım sunucu güncellemesi henüz uygulanmadı.':c.errorText(ex));f.querySelector('button').disabled=false;}};
 }catch(e){if(ctx===c&&n===seq)root.innerHTML=`<h1>Bakım modu</h1><p class="hata">${c.esc(e.code==='PGRST202'?'Bakım sunucu güncellemesi henüz uygulanmadı.':c.errorText(e))}</p>`;}}
function route(h){if(h.split('?')[0]!=='bakim')return false;if(!ctx?.caps.owner){location.hash='ozet';return true;}load();return true;}
window.PuffyBakim={init,stop,route};})();
