/* İletişim metadata; private content is never requested or rendered. */
(() => {
 'use strict';
 const n=x=>new Intl.NumberFormat('tr-TR').format(Number(x||0));
 const kinds={text:'Metin',image:'Görsel',gift:'Hediye',system:'Sistem bildirimi',audio:'Sesli',video:'Görüntülü'};
 const statuses={ended:'Sonlandı',cancelled:'İptal',declined:'Reddedildi',missed:'Cevapsız',ringing:'Çalıyor',accepted:'Kabul edildi',connected:'Bağlı',active:'Aktif',timeout:'Zaman aşımı',failed:'Başarısız',busy:'Meşgul'};
 const events={message_deleted:'Mesaj silinmiş işareti',message_hidden:'Mesaj benden gizlendi',conversation_cleared:'Sohbet benden temizlendi',conversation_archived:'Sohbet arşivlendi',call_hidden:'Arama benden gizlendi',call_history_cleared:'Arama geçmişi benden temizlendi'};
 const warnings={STATUS_CONNECTION_CONFLICT:'Durum ile bağlantı zamanı çelişiyor',NEGATIVE_DURATION:'Bitiş bağlantıdan önce',ENDED_WITHOUT_CONNECTION:'Sonlanmış fakat bağlantı zamanı yok',ENDED_WITHOUT_END_TIME:'Sonlanmış fakat bitiş zamanı yok',ACTIVE_WITH_END_TIME:'Aktif durum fakat bitiş zamanı var'};
 const sections={peers:'Kişilere göre mesajlar',calls:'Birebir aramalar',group_calls:'Grup arama davetleri',events:'Silme / gizleme kayıtları'};
 function duration(s){if(s==null)return '—';s=Math.max(0,Math.round(Number(s)));return Math.floor(s/3600)?`${Math.floor(s/3600)} sa ${Math.floor(s%3600/60)} dk ${s%60} sn`:`${Math.floor(s/60)} dk ${s%60} sn`;}
 function dayBoundary(value,end=false){if(!value)return null;if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw Error('INVALID_DATE_RANGE');const d=new Date(value+'T00:00:00+03:00');if(!Number.isFinite(+d)||new Date(+d+10800000).toISOString().slice(0,10)!==value)throw Error('INVALID_DATE_RANGE');return new Date(+d+(end?86400000:0)).toISOString();}
 function params(user,filters,section,offset=0){const from=dayBoundary(filters.start),to=dayBoundary(filters.end,true);if(from&&to&&from>=to)throw Error('INVALID_DATE_RANGE');return {p_user:user,p_from:from,p_to:to,...(section?{p_section:section,p_peer:filters.peer||null,p_limit:25,p_offset:offset}:{})};}
 function tabs(ctx){return ctx.caps?.actions?.sensitive_read?{communication:'Mesajlar ve aramalar'}:{};}
 function renderTab(key,ctx){if(key!=='communication')return;const {root,profile,rpc,esc,errorText}=ctx;if(!tabs(ctx).communication){root.textContent='Bu bölüme erişim yetkin yok.';return;}
 const stamp=s=>s?new Date(s).toLocaleString('tr-TR',{timeZone:'Europe/Istanbul',dateStyle:'medium',timeStyle:'medium'}):'—';
 const person=(id,name,display)=>id?`<a href="#kullanici/${esc(id)}">${esc(name||'İsim yok')} <small>ID ${esc(display??'—')}</small></a>`:'Bilinmiyor';
 const table=(heads,rows)=>rows.length?`<div class="iletisim-table"><table><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p class="empty-state">Bu filtrede kayıt yok.</p>';
 let section='peers',offset=0,filters={start:'',end:'',peer:null},ticket=0,summaryTicket=0,peerLabel='';
 root.innerHTML=`<section class="iletisim"><div class="eyebrow">İLETİŞİM DENETİMİ</div><h2>Mesajlar ve aramalar</h2><p class="note">Yalnız adet, taraf, zaman ve durum bilgisi. Görüntüleme işlem kütüğüne kaydedilir.</p><form class="iletisim-filter"><label>Başlangıç<input name="start" type="date"></label><label>Bitiş (dahil)<input name="end" type="date"></label><button class="primary" type="submit">Uygula</button><button type="button" data-reset>Tüm zamanlar</button></form><p class="note">Saat dilimi: Türkiye (Europe/Istanbul). Özet mesaj/arama oluşturma tarihine, silme/gizleme listesi işlem tarihine göre filtrelenir.</p><div data-summary aria-live="polite"></div><div class="iletisim-sections" role="group" aria-label="İletişim listeleri">${Object.entries(sections).map(([k,v])=>`<button type="button" data-section="${k}" aria-pressed="${k===section}">${v}</button>`).join('')}</div><div data-peer hidden><span></span> <button type="button">Kişi filtresini kaldır</button></div><div data-list aria-live="polite"></div><p class="note">Silinmiş işareti, görsel dosyasının depolamadan kaldırıldığını veya kimin sildiğini kanıtlamaz. Benden gizleme/temizleme kayıtlarında işlemi yapan kullanıcı bellidir. Bu listeler mevcut kayıtların dökümüdür; kalıcı silinen satırlar, geri alınan gizlemeler ve önceki temizlemeler bulunmayabilir.</p></section>`;
 const box=root.querySelector('[data-list]'),summary=root.querySelector('[data-summary]'),form=root.querySelector('form');
 const alive=t=>t===ticket&&root.isConnected;
 function failure(el,e,retry){el.innerHTML=`<div class="alert error" role="alert">${esc(e.message==='INVALID_DATE_RANGE'?'Başlangıç ve bitiş tarihini kontrol et.':errorText(e))} <button type="button">Tekrar dene</button></div>`;el.querySelector('button').onclick=retry;}
 function summaryView(d){const m=d.messages||{},c=d.calls||[],g=d.group_calls||[],sum=(a,k)=>a.reduce((s,r)=>s+Number(r[k]||0),0),audio=c.filter(x=>x.kind==='audio'),video=c.filter(x=>x.kind==='video');
 const metrics=[['Özel mesaj',m.total],['Gönderilen',m.sent],['Gelen',m.received],['Mesajlaşılan kişi',m.peers],['Silinmiş mesaj',m.deleted],['Silinmiş görsel',m.deleted_images],['Sesli arama girişimi',sum(audio,'total')],['Görüntülü arama girişimi',sum(video,'total')],['Tutarsız arama',sum(c,'inconsistent')],['Oda mesajı (giden)',d.other_messages?.room_sent],['Grup mesajı (giden)',d.other_messages?.group_sent]];
 summary.innerHTML=`<div class="metrics">${metrics.map(([label,value])=>`<div class="metric"><span>${esc(label)}</span><strong>${n(value)}</strong></div>`).join('')}</div><p class="note">Mesaj toplamında ${n(m.system)} sistem bildirimi ayrı tutulur; silinmiş satırlar toplama dahildir. Tutarlı sonlanmış sesli: ${n(sum(audio,'completed'))} / ${duration(sum(audio,'seconds'))}; görüntülü: ${n(sum(video,'completed'))} / ${duration(sum(video,'seconds'))}. Bağlantı işareti tek başına başarılı görüşme değildir.</p>${sum(c,'inconsistent')?`<p class="alert error" role="alert">${n(sum(c,'inconsistent'))} aramada kayıt tutarsızlığı var. Ayrıntıları Birebir aramalar listesinden inceleyin.</p>`:''}<details><summary>Mesaj türleri ve günlük hareket</summary>${table(['Tür','Giden','Gelen','Silinmiş'],(d.message_kinds||[]).map(r=>[esc(kinds[r.kind]||r.kind),n(r.sent),n(r.received),n(r.deleted)]))}${table(['Gün (Türkiye)','Giden','Gelen','Toplam'],(d.daily||[]).map(r=>[esc(r.day),n(r.sent),n(r.received),n(Number(r.sent)+Number(r.received))]))}</details><details><summary>Arama durumları ve grup katılımları</summary>${table(['Tür','Yön','Durum','Adet','Bağlantı işareti','Tutarsız','Tutarlı biten','Süre'],c.map(r=>[esc(kinds[r.kind]||r.kind),r.direction==='outgoing'?'Giden':'Gelen',esc(statuses[r.status]||r.status),n(r.total),n(r.connection_marked),n(r.inconsistent),n(r.completed),duration(r.seconds)]))}${table(['Grup türü','Davet/kayıt','Katılım zamanı var','Kayıtlı katılım süresi'],g.map(r=>[esc(kinds[r.kind]||r.kind),n(r.total),n(r.joined),duration(r.seconds)]))}</details><p class="note">Özet veri zamanı: ${esc(stamp(d.as_of))}</p>`;
 }
 function listView(d){const rows=d.rows||[];let heads,cells;
 if(section==='peers'){heads=['Karşı taraf','Giden','Gelen','Toplam','Silinmiş','Son mesaj','İncele'];cells=rows.map(r=>[person(r.other_id,r.nickname,r.display_id),n(r.sent),n(r.received),n(r.total),n(r.deleted),esc(stamp(r.last_at)),`<button data-person="${esc(r.other_id)}" data-name="${esc(r.nickname||'İsim yok')}" data-target="calls">Aramalar</button> <button data-person="${esc(r.other_id)}" data-name="${esc(r.nickname||'İsim yok')}" data-target="events">Silme/gizleme</button>`]);}
 if(section==='calls'){heads=['Zaman','Arayan → Aranan','Tür','Durum','Bağlantı','Bitiş','Kayıtlı süre','Uyarı'];cells=rows.map(r=>[esc(stamp(r.created_at)),`${person(r.caller_id,r.caller_name,r.caller_display_id)} → ${person(r.callee_id,r.callee_name,r.callee_display_id)}`,esc(kinds[r.kind]||r.kind),esc(statuses[r.status]||r.status),esc(stamp(r.connected_at)),esc(stamp(r.ended_at)),duration(r.recorded_seconds),(r.warnings||[]).map(w=>`<span class="tag bad">${esc(warnings[w]||w)}</span>`).join(' ')||'—']);}
 if(section==='group_calls'){heads=['Başlangıç','Başlatan','Grup UUID','Tür','Arama durumu','Katılımcı durumu','Davet','Katıldı','Ayrıldı','Kayıtlı süre'];cells=rows.map(r=>[esc(stamp(r.created_at)),person(r.created_by,r.creator_name,r.creator_display_id),esc(r.group_id||'—'),esc(kinds[r.kind]||r.kind),esc(statuses[r.status]||r.status),esc(({invited:'Davet edildi',joined:'Katıldı',declined:'Reddedildi',left:'Ayrıldı'})[r.state]||r.state),esc(stamp(r.invited_at)),esc(stamp(r.joined_at)),esc(stamp(r.left_at)),duration(r.recorded_seconds)]);}
 if(section==='events'){heads=['İşlem zamanı','İşlem','İşlemi yapan','Mesajı/aramayı başlatan','Karşı taraf','Tür','Kaynak zamanı','Kayıt ID'];cells=rows.map(r=>[esc(stamp(r.event_at)),esc(events[r.event]||r.event),person(r.actor_id,r.actor_name,r.actor_display_id),person(r.sender_id,r.sender_name,r.sender_display_id),person(r.other_id,r.other_name,r.other_display_id),esc(kinds[r.kind]||r.kind||'—'),esc(stamp(r.source_at)),esc(r.record_id)]);}
 box.innerHTML=`<h3>${esc(sections[section])}</h3>${table(heads,cells)}<div class="pager"><span>${n(d.total)} kayıt · ${d.total?n(offset+1):0}–${n(Math.min(offset+rows.length,d.total))}</span><button data-prev ${offset===0?'disabled':''}>Önceki</button><button data-next ${offset+25>=d.total?'disabled':''}>Sonraki</button></div><p class="note">Liste veri zamanı: ${esc(stamp(d.as_of))}</p>`;
 box.querySelector('[data-prev]').onclick=()=>{offset=Math.max(0,offset-25);load(false);};box.querySelector('[data-next]').onclick=()=>{offset+=25;load(false);};
 box.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{filters.peer=b.dataset.person;peerLabel=b.dataset.name;section=b.dataset.target;offset=0;load(false);});
 }
 async function load(withSummary){const t=++ticket;root.querySelectorAll('[data-section]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.section===section)));const peer=root.querySelector('[data-peer]');peer.hidden=!filters.peer;peer.querySelector('span').textContent=peerLabel?'Kişi filtresi: '+peerLabel:'';box.textContent='Liste yükleniyor…';let listParams,summaryParams;try{listParams=params(profile.id,filters,section,offset);summaryParams=params(profile.id,filters);}catch(e){failure(box,e,()=>load(withSummary));return;}
 if(withSummary){const st=++summaryTicket;summary.textContent='Özet yükleniyor…';rpc('yonetim_kullanici_iletisim',summaryParams).then(d=>{if(st===summaryTicket&&root.isConnected)summaryView(d);}).catch(e=>{if(st===summaryTicket&&root.isConnected)failure(summary,e,()=>load(true));});}
 try{const d=await rpc('yonetim_kullanici_iletisim_listesi',listParams);if(alive(t))listView(d);}catch(e){if(alive(t))failure(box,e,()=>load(false));}
 }
 form.onsubmit=e=>{e.preventDefault();filters.start=form.elements.start.value;filters.end=form.elements.end.value;offset=0;load(true);};root.querySelector('[data-reset]').onclick=()=>{form.reset();filters={start:'',end:'',peer:null};peerLabel='';offset=0;load(true);};root.querySelector('[data-peer] button').onclick=()=>{filters.peer=null;peerLabel='';offset=0;load(false);};root.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;offset=0;load(false);});load(true);
 }
 window.PuffyIletisim={tabs,renderTab,params,duration};
})();
