(() => {
'use strict';let ctx=null,serial=0;const labels={bekliyor:'Bekliyor',onaylandi:'Onaylandı',tamamlandi:'Tamamlandı',reddedildi:'Reddedildi',suresi_doldu:'Süresi doldu'};
const json=(c,v)=>'<pre style="white-space:pre-wrap;overflow-wrap:anywhere">'+c.esc(v==null?'—':JSON.stringify(v,null,2))+'</pre>';
function stop(){serial++;ctx=null;document.querySelector('#scope-nav')?.remove();document.querySelector('#s-kapsam')?.replaceChildren();}
function init(c){stop();ctx=c;if(!c.caps.admin)return;const n=document.createElement('div');n.id='scope-nav';n.innerHTML='<a class="menu" href="#hesap-talepleri">Hesap kurtarma / devir</a><a class="menu" href="#acilis-afisleri">Açılış afişleri</a>';document.querySelector('#uyg nav').append(n);if(!document.querySelector('#s-kapsam')){const r=document.createElement('section');r.id='s-kapsam';r.className='hidden';document.querySelector('.workspace').append(r);}}
function route(hash){const [name,query]=hash.split('?');if(!['oyun-kasasi','hesap-talepleri','acilis-afisleri'].includes(name))return false;if(!ctx?.caps.admin){location.hash='ozet';return true;}load(name,new URLSearchParams(query));return true;}
function pager(root,total,page,go){const el=document.createElement('div');el.className='pager';el.innerHTML=`<span>${Number(total)||0} kayıt · sayfa ${page+1}</span><button data-prev ${page===0?'disabled':''}>Önceki</button><button data-next ${(page+1)*25>=total?'disabled':''}>Sonraki</button>`;root.append(el);el.querySelector('[data-prev]').onclick=()=>go(page-1);el.querySelector('[data-next]').onclick=()=>go(page+1);}
function dialog(c,title,body){const d=document.createElement('dialog');d.innerHTML='<h2>'+c.esc(title)+'</h2>'+body+'<button data-close>Kapat</button>';document.body.append(d);d.showModal();d.onclose=()=>d.remove();d.querySelector('[data-close]').onclick=()=>d.close();return d;}
async function load(name,q){const c=ctx,n=++serial,r=document.querySelector('#s-kapsam'),page=Math.max(0,Number(q.get('sayfa'))||0);document.querySelectorAll('.workspace > [id^="s-"]').forEach(e=>e.classList.toggle('hidden',e!==r));r.innerHTML='<p role="status">Yükleniyor…</p>';const current=()=>ctx===c&&serial===n;const go=p=>{q.set('sayfa',p);location.hash=name+'?'+q;};
try{
 if(name==='oyun-kasasi'){
 const inventory=await c.rpc('yonetim_oyun_envanteri');if(!current())return;const game=q.get('oyun')||'mahzen',meta=inventory.find(x=>x.kod===game);if(!meta)throw Error('Geçersiz oyun');const d=await c.rpc('yonetim_oyun_incele',{p_oyun:game,p_limit:25,p_offset:page*25,p_id:q.get('id')||null});if(!current())return;
 r.innerHTML='<h1>Oyun denetimi</h1><nav>'+inventory.map(g=>`<a class="chip" href="#oyun-kasasi?oyun=${encodeURIComponent(g.kod)}">${c.esc(g.ad)}${g.hazir?'':' · şema yok'}</a>`).join(' ')+'</nav><h2>'+c.esc(meta.ad)+'</h2><p>'+c.esc(d.not)+'</p><p>Para birimi: '+c.esc(meta.para_birimi)+' · Görünürlük ayarı: '+c.esc(meta.gorunurluk==null?'Tanımlı değil':JSON.stringify(meta.gorunurluk))+'</p>';
 if(!d.hazir)return;
 for(const [key,title] of [['son24','Son 24 saat · bahis / ödeme / RTP / isabet'],['kasa','Kasa ve ayrılan tutar'],['bonus','Serbest dönüş / açık bonus'],['cizgiler','Çizgi dağılımı'],['en_buyuk_odemeler','En büyük 10 ödeme'],['mutabakat','Kayıt mutabakatı'],['ayar','Oyun ayarı'],['katilimlar','Katılımcılar']]){const box=document.createElement('details');box.innerHTML='<summary>'+title+'</summary>'+json(c,d[key]);r.append(box);}
 const list=document.createElement('section');list.innerHTML='<h2>Tur / maç / işlem kayıtları</h2>'+d.rows.map(x=>{const id=x.istek_id??x.tur_no??x.id;return '<article class="panel"><a href="#oyun-kasasi?oyun='+encodeURIComponent(game)+'&id='+encodeURIComponent(id)+'">Kaydı ve katılımları incele</a>'+json(c,x)+'</article>';}).join('');r.append(list);pager(r,d.total,page,go);
 }else if(name==='hesap-talepleri'){
 const status=q.get('durum')||'',d=await c.rpc('yonetim_hesap_talepleri',{p_durum:status||null,p_limit:25,p_offset:page*25});if(!current())return;
 r.innerHTML='<h1>Hesap kurtarma / devir talepleri</h1><label>Durum<select><option value="">Tümü</option>'+Object.entries(labels).map(([k,v])=>`<option value="${k}" ${k===status?'selected':''}>${v}</option>`).join('')+'</select></label>'+d.rows.map((x,i)=>`<article class="panel"><strong>${c.esc(x.display_id)} · ${c.esc(x.tur)}</strong><p>${c.esc(labels[x.durum]||x.durum)} · ${c.esc(x.iletisim_maskeli||'')} · Süre: ${Math.round(Number(x.sure_saniye)/60)} dk</p><p>${c.esc(c.date(x.created_at))} · ${c.esc(x.karar_notu||'')}</p><button data-detail="${i}">Kanıt ve karar geçmişi</button></article>`).join('');
 r.querySelector('select').onchange=e=>{q.set('durum',e.target.value);go(0);};pager(r,d.total,page,go);
 r.querySelectorAll('[data-detail]').forEach(b=>b.onclick=async()=>{try{const row=d.rows[Number(b.dataset.detail)],a=await c.rpc('yonetim_hesap_talebi_detay',{p_id:row.id});if(!current())return;const x=a[0];if(!x)throw Error('Talep bulunamadı');const dlg=dialog(c,'Talep kanıtı ve geçmişi',json(c,x)+(x.durum==='bekliyor'?'<form><label>Karar gerekçesi<textarea name="note" required minlength="3" maxlength="1000"></textarea></label><button name="decision" value="yes">Onayla</button><button name="decision" value="no">Reddet</button><p role="alert"></p></form>':''));const form=dlg.querySelector('form');if(form)form.onsubmit=async e=>{e.preventDefault();const yes=e.submitter?.value==='yes';form.querySelectorAll('button').forEach(b=>b.disabled=true);try{await c.rpc('admin_hesap_talebi_karar',{p_talep_id:row.id,p_onay:yes,p_not:form.elements.note.value});dlg.close();if(current())load(name,q);}catch(err){form.querySelector('[role=alert]').textContent=c.errorText(err);form.querySelectorAll('button').forEach(b=>b.disabled=false);}};}catch(e){if(current())c.toast(c.errorText(e));}});
 }else{
 const data=await c.rpc('acilis_afisleri_admin');if(!current())return;const rows=Array.isArray(data)?data:[];r.innerHTML='<h1>Açılış afişleri</h1><p>Uygulamanın açılış ekranı; ana sayfa banner alanından ayrıdır.</p><button data-new>Görsel afiş ekle</button>'+rows.map((x,i)=>`<article class="panel"><h2>${c.esc(x.baslik||x.tur)}</h2>${image(c,x.gorsel)}<p>${x.aktif?'Aktif':'Pasif'} · ${c.esc(x.donem||'')} · sıra ${c.esc(x.sira)} · ${c.esc(c.date(x.baslangic))} — ${c.esc(c.date(x.bitis))}</p><button data-edit="${i}">Düzenle / pasifleştir</button></article>`).join('');r.querySelector('[data-new]').onclick=()=>editSplash(c,{},()=>load(name,q));r.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editSplash(c,rows[Number(b.dataset.edit)],()=>load(name,q)));
 }
}catch(e){if(current()){r.innerHTML='<p role="alert">'+c.esc(c.errorText(e))+'</p><button>Tekrar dene</button>';r.querySelector('button').onclick=()=>load(name,q);}}}
function image(c,path){const url=/^https?:/.test(path||'')?c.safeUrl(path):path?c.sb.storage.from('room-images').getPublicUrl(path.replace(/^room-images\//,'')).data.publicUrl:'';return url?'<img style="max-width:280px;max-height:200px;object-fit:contain" src="'+c.esc(url)+'" alt="Afiş önizleme">':'';}
function editSplash(c,row,refresh){const dt=v=>v?new Date(v).toISOString().slice(0,16):'';const d=dialog(c,'Açılış afişi','<form><label>Başlık<input name="title" value="'+c.esc(row.baslik||'')+'" maxlength="100"></label><label><input name="active" type="checkbox" '+(row.aktif?'checked':'')+'>Aktif</label><label>Dönem<select name="period"><option value="haftalik">Haftalık</option><option value="aylik">Aylık</option></select></label><label>Görsel yolu / HTTPS adresi<input name="path" value="'+c.esc(row.gorsel||'')+'"></label><label>Görsel yükle<input type="file" name="file" accept="image/jpeg,image/png,image/webp"></label><div data-preview>'+image(c,row.gorsel)+'</div><label>Başlangıç (UTC)<input name="start" type="datetime-local" value="'+dt(row.baslangic)+'"></label><label>Bitiş (UTC)<input name="end" type="datetime-local" value="'+dt(row.bitis)+'"></label><label>Sıra<input name="order" type="number" value="'+Number(row.sira||0)+'"></label><p role="alert"></p><button>Kaydet</button></form>');const f=d.querySelector('form');f.elements.period.value=row.donem||'haftalik';if(row.id&&row.tur!=='gorsel'){f.elements.path.disabled=true;f.elements.file.disabled=true;}f.elements.path.onchange=()=>d.querySelector('[data-preview]').innerHTML=image(c,f.elements.path.value);let uploaded=null;f.onsubmit=async e=>{e.preventDefault();f.querySelector('button').disabled=true;try{let path=f.elements.path.value;const file=f.elements.file.files[0];if(file&&!uploaded){const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type];if(!ext||file.size>5*1024*1024)throw Error('PNG, JPEG veya WebP, en fazla 5 MB gerekir.');const key='acilis/'+crypto.randomUUID()+'.'+ext;const result=await c.sb.storage.from('room-images').upload(key,file,{contentType:file.type,upsert:false});if(result.error)throw result.error;uploaded='room-images/'+key;}if(uploaded)path=uploaded;await c.rpc('acilis_afisi_kaydet',{p_id:row.id||null,p_tur:row.tur||'gorsel',p_aktif:f.elements.active.checked,p_donem:f.elements.period.value,p_gorsel_path:path||null,p_baslik:f.elements.title.value||null,p_baslangic:f.elements.start.value?f.elements.start.value+':00Z':null,p_bitis:f.elements.end.value?f.elements.end.value+':00Z':null,p_sira:Number(f.elements.order.value)});d.close();if(ctx===c)refresh();}catch(err){f.querySelector('[role=alert]').textContent=c.errorText(err);f.querySelector('button').disabled=false;}};}
function financeParams(user,kind,filters,page){return {p_user:user,p_tur:kind,p_baslangic:filters.start?filters.start+'T00:00:00Z':null,p_bitis:filters.end?new Date(Date.parse(filters.end+'T00:00:00Z')+86400000).toISOString():null,p_arama:filters.search||null,p_islem:filters.type||null,p_limit:25,p_offset:page*25};}
function renderFinance(kind,c){const root=c.root;let page=0,seq=0;const filters={};root.innerHTML='<form><label>Başlangıç (UTC)<input name="start" type="date"></label><label>Bitiş (UTC, dahil)<input name="end" type="date"></label><label>Referans / ürün / kayıt ID<input name="search"></label><label>İşlem türü / durum<input name="type"></label><button>Filtrele</button></form><div data-finance></div>';root.querySelector('form').onsubmit=e=>{e.preventDefault();Object.assign(filters,Object.fromEntries(new FormData(e.target)));page=0;loadPage();};async function loadPage(){const s=++seq,box=root.querySelector('[data-finance]');box.textContent='Yükleniyor…';try{const d=await c.rpc('yonetim_kullanici_finans_gecmisi',financeParams(c.profile.id,kind,filters,page));if(s!==seq||!root.isConnected||!root.contains(box))return;box.innerHTML=d.rows.map(x=>'<article class="panel">'+json(c,x)+'</article>').join('')||'<p>Kayıt yok.</p>';pager(box,d.total,page,p=>{page=p;loadPage();});}catch(e){if(s===seq&&root.contains(box)){box.innerHTML='<p role="alert">'+c.esc(c.errorText(e))+'</p><button>Tekrar dene</button>';box.querySelector('button').onclick=loadPage;}}}loadPage();}
window.PuffyKapsam={init,stop,route,renderFinance,financeParams};
})();
