(function(root){
 'use strict';
 class RequestGate{constructor(){this.seq=0;}next(){return ++this.seq;}valid(token){return token===this.seq;}invalidate(){this.seq++;}}
 function media(src,title,type,esc,safeUrl){const u=safeUrl(src);if(!u)return '<p>Medya bulunamadı.</p>';const video=type==='video'||String(type||'').startsWith('video/')||/\.(mp4|webm|mov)(?:[?#]|$)/i.test(u);return `<figure>${video?`<video src="${esc(u)}" controls preload="metadata" playsinline></video>`:`<img src="${esc(u)}" alt="${esc(title)}" loading="lazy" referrerpolicy="no-referrer">`}<figcaption>${esc(title)}</figcaption></figure>`;}
 function checkResult(result){if(!result||result.ok!==true)throw new Error(result?.error||'OPERATION_REJECTED');return result;}
 let ctx=null,serial=0,page=0;
 function init(c){stop();ctx=c;if(!c.caps.moderator)return;const nav=document.createElement('div');nav.id='moderation-nav';nav.innerHTML='<a class="menu" href="#moderasyon-gecmis">Şikayet dosyaları</a>';document.querySelector('#uyg nav').append(nav);if(!document.querySelector('#s-dosyalar')){const section=document.createElement('section');section.id='s-dosyalar';section.className='hidden';document.querySelector('.workspace').append(section);}}
 function stop(){serial++;ctx=null;document.querySelector('#moderation-nav')?.remove();document.querySelector('#s-dosyalar')?.replaceChildren();}
 async function showCase(source,id){const c=ctx;if(!c)return;try{const d=await c.rpc('yonetim_sikayet_dosyasi',{p_kaynak:source,p_id:id});if(c!==ctx)return;const dlg=document.createElement('dialog');dlg.className='phase2-dialog';const content=d.kanit?.icerik||{};dlg.innerHTML=`<h2>Şikayet dosyası</h2><p>${c.esc(d.durum)} · ${c.esc(id)}</p>${content.video_url?media(content.video_url,'Kanıt videosu','video',c.esc,c.safeUrl):''}<pre>${c.esc(JSON.stringify(d,null,2))}</pre>${d.durum==='bekliyor'?`<form><label>Sorumlu moderatör UUID (boş: atanmamış)<input name="owner" value="${c.esc(d.atanan||'')}"></label><label>Hedef tarih<input name="due" type="datetime-local"></label><label>Devir notu<textarea name="note" maxlength="1000">${c.esc(d.notlar||'')}</textarea></label><button>Atamayı kaydet</button><p role="alert"></p></form>`:''}<button data-close>Kapat</button>`;document.body.append(dlg);dlg.showModal();dlg.onclose=()=>dlg.remove();dlg.querySelector('[data-close]').onclick=()=>dlg.close();const form=dlg.querySelector('form');if(form)form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);try{await c.rpc('yonetim_sikayet_ata',{p_kaynak:source,p_id:id,p_atanan:String(f.get('owner')||'').trim()||null,p_son_tarih:f.get('due')?new Date(String(f.get('due'))).toISOString():null,p_not:String(f.get('note')||'')});dlg.close();c.toast('Atama kaydedildi.');}catch(err){form.querySelector('[role=alert]').textContent=c.errorText(err);}};}catch(e){c.toast(c.errorText(e));}}
 function route(hash){if(hash!=='moderasyon-gecmis')return false;if(!ctx?.caps.moderator){location.hash='ozet';return true;}page=0;load();return true;}
 async function load(){const c=ctx,n=++serial,r=document.querySelector('#s-dosyalar');document.querySelectorAll('.workspace > [id^="s-"]').forEach(e=>e.classList.toggle('hidden',e!==r));r.innerHTML='<h1>Şikayet dosyaları ve geçmiş</h1><p>Yeni kararların kanıtı, gerekçesi ve aktörü korunur. Eski arşivlerde yalnız o tarihte kaydedilmiş bilgiler bulunur.</p>';try{const d=await c.rpc('yonetim_sikayet_gecmisi',{p_limit:25,p_offset:page*25});if(ctx!==c||n!==serial)return;r.innerHTML+=d.rows.map((x,i)=>`<article class="panel"><b>${c.esc(x.durum)} · ${c.esc(x.kaynak)}</b><p>${c.esc(x.gerekce||x.notlar||'')}</p><small>Sorumlu: ${c.esc(x.atanan||'Atanmamış')} · Hedef: ${c.esc(x.son_tarih||'Belirlenmedi')} · Karar: ${c.esc(x.karar_veren||'—')}</small><button data-case="${i}">Dosyayı aç</button></article>`).join('')+`<div class="pager"><span>${c.esc(d.total)} dosya</span><button data-prev ${page?'':'disabled'}>Önceki</button><button data-next ${(page+1)*25>=d.total?'disabled':''}>Sonraki</button></div>`;r.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{const x=d.rows[Number(b.dataset.case)];showCase(x.kaynak,x.sikayet_id);});r.querySelector('[data-prev]').onclick=()=>{page--;load();};r.querySelector('[data-next]').onclick=()=>{page++;load();};}catch(e){if(ctx===c&&n===serial){r.innerHTML+='<p role="alert">'+c.esc(c.errorText(e))+'</p><button data-retry>Tekrar dene</button>';r.querySelector('[data-retry]').onclick=load;}}}
 root.PuffyModeration={RequestGate,media,checkResult,init,stop,route,showCase};if(typeof module!=='undefined')module.exports=root.PuffyModeration;
})(typeof window==='undefined'?globalThis:window);
