(() => {
 'use strict';let ctx=null,serial=0,kind='para_cekme',status='',page=0;
 const labels={belirsiz:'Tarihsel ödeme doğrulanmalı',odeme_bekliyor:'Ödeme bekliyor',odendi:'Ödendi',basarisiz:'Başarısız',iade:'İade'};
 const next={belirsiz:['odeme_bekliyor','odendi'],odeme_bekliyor:['odendi','basarisiz'],basarisiz:['odeme_bekliyor','iade'],odendi:['iade'],iade:[]};
 function stop(){serial++;ctx=null;document.querySelector('#payment-nav')?.remove();document.querySelector('#s-odemeler')?.replaceChildren();}
 function init(c){stop();ctx=c;if(!c.caps.admin)return;const nav=document.createElement('div');nav.id='payment-nav';nav.innerHTML='<div class="nav-caption">Ödeme takibi</div><a class="menu" href="#odemeler/para_cekme">Banka ödemeleri</a><a class="menu" href="#odemeler/puffy_dolar">Puffy Dolar</a>';document.querySelector('#uyg nav').append(nav);if(!document.querySelector('#s-odemeler')){const root=document.createElement('section');root.id='s-odemeler';root.className='hidden';document.querySelector('.workspace').append(root);}}
 function route(hash){if(!hash.startsWith('odemeler/'))return false;if(!ctx?.caps.admin){location.hash='ozet';return true;}kind=hash.split('/')[1];if(!['para_cekme','puffy_dolar'].includes(kind)){location.hash='ozet';return true;}page=0;status='';load();return true;}
 async function load(){const c=ctx,n=++serial,k=kind,root=document.querySelector('#s-odemeler');document.querySelectorAll('.workspace > [id^="s-"]').forEach(e=>e.classList.toggle('hidden',e!==root));root.innerHTML='<h1>'+ (k==='puffy_dolar'?'Puffy Dolar':'Banka ödemeleri')+'</h1><p>Onay banka transferi değildir. Ödendi ve iade kararlarında gerçek banka/işlem referansı gerekir.</p><div data-content>Yükleniyor…</div>';
  try{const d=await c.rpc('yonetim_odeme_listesi',{p_tur:k,p_durum:status||null,p_limit:25,p_offset:page*25});if(ctx!==c||n!==serial)return;
   const box=root.querySelector('[data-content]');box.innerHTML='<label>Durum<select data-filter><option value="">Tümü</option>'+Object.entries(labels).map(([v,l])=>`<option value="${v}" ${status===v?'selected':''}>${l}</option>`).join('')+'</select></label>'+d.rows.map((r,i)=>`<article class="panel"><strong>${c.esc(r.nickname||r.user_id)}</strong><p>${c.esc(r.usd)} USD · ${c.esc(labels[r.durum]||r.durum)}${r.net_tl!=null?' · '+c.esc(r.net_tl)+' TL':''}</p><small>${c.esc(r.id)} · ${c.esc(r.banka_referansi||'Referans yok')}</small><button data-detail="${i}">Banka ve geçmiş</button>${(next[r.durum]||[]).map(s=>`<button data-action="${s}" data-row="${i}">${labels[s]}</button>`).join('')}</article>`).join('')+(d.rows.length?'':'<p>Bu filtrede kayıt yok.</p>')+`<div class="pager"><span>${c.esc(d.total)} kayıt</span><button data-prev ${page===0?'disabled':''}>Önceki</button><button data-next ${(page+1)*25>=d.total?'disabled':''}>Sonraki</button></div>`;
   box.querySelector('[data-filter]').onchange=e=>{status=e.target.value;page=0;load();};box.querySelector('[data-prev]').onclick=()=>{page--;load();};box.querySelector('[data-next]').onclick=()=>{page++;load();};
   box.querySelectorAll('[data-detail]').forEach(b=>b.onclick=async()=>{try{const detail=await c.rpc('yonetim_odeme_detayi',{p_tur:k,p_id:d.rows[Number(b.dataset.detail)].id});if(ctx!==c||n!==serial)return;const dlg=document.createElement('dialog');dlg.innerHTML='<h2>Banka ve ödeme geçmişi</h2><pre>'+c.esc(JSON.stringify(detail,null,2))+'</pre><button>Kapat</button>';document.body.append(dlg);dlg.showModal();dlg.querySelector('button').onclick=()=>dlg.close();dlg.onclose=()=>dlg.remove();}catch(e){c.toast(c.errorText(e));}});
   box.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>decide(c,k,d.rows[Number(b.dataset.row)],b.dataset.action));
  }catch(e){if(ctx===c&&n===serial){root.querySelector('[data-content]').innerHTML='<p role="alert">'+c.esc(c.errorText(e))+'</p><button data-retry>Tekrar dene</button>';root.querySelector('[data-retry]').onclick=load;}}}
 function decide(c,k,row,to){const dlg=document.createElement('dialog');const id=crypto.randomUUID();dlg.innerHTML=`<form><h2>${c.esc(labels[to])}</h2><p>${c.esc(row.nickname)} · ${c.esc(row.usd)} USD · ${c.esc(row.id)}</p>${to==='iade'?'<p>İade bakiyeye bir kez geri eklenir. Bankadan geri gelen tutarı veya başarısız ödeme kaydını doğrulayın.</p>':''}<label>Banka/işlem referansı<input name="ref" maxlength="200" ${['odendi','iade'].includes(to)?'required minlength="3"':''}></label><label>Gerekçe<textarea name="reason" minlength="3" maxlength="300" required></textarea></label><p role="alert"></p><button type="button">Vazgeç</button><button>Kararı kaydet</button></form>`;document.body.append(dlg);dlg.showModal();dlg.onclose=()=>dlg.remove();dlg.querySelector('[type=button]').onclick=()=>dlg.close();let busy=false;dlg.oncancel=e=>{if(busy)e.preventDefault();};dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy||ctx!==c)return;busy=true;dlg.querySelectorAll('button').forEach(b=>b.disabled=true);const f=new FormData(e.target);try{await c.rpc('yonetim_odeme_islemi',{p_tur:k,p_id:row.id,p_durum:to,p_referans:String(f.get('ref')||''),p_neden:String(f.get('reason')),p_request_id:id});dlg.close();if(ctx===c){c.toast('Ödeme durumu kaydedildi.');load();}}catch(err){dlg.querySelector('[role=alert]').textContent=c.errorText(err);busy=false;dlg.querySelectorAll('button').forEach(b=>b.disabled=false);}};}
 window.PuffyOdemeler={init,stop,route};
})();
