/* Puffy Yönetim Faz 2 — bütün işlemler kullanıcının MFA oturumu ile sunucuda denetlenir. */
(() => {
 'use strict';
 const tabs={content:'İçerik',notes:'Notlar',audit:'Kütük'};
 const labels={ban:'Süreli / kalıcı ban',unban:'Platform banını kaldır',deviceBan:'Cihaz banı',deviceUnban:'Cihaz banını kaldır',mute:'Süreli susturma',unmute:'Susturmayı kaldır',warn:'Kayıtlı uyarı gönder',kick:'Odalardan çıkar',closeRooms:'Odalardan çıkar ve kendi odalarını kapat',logout:'Tüm oturumları sonlandır',avatar:'Avatarı değiştir / kaldır',profile:'Ad, bio ve kapak temizliği',note:'Yönetici notu ekle'};
 const auditNames={hesap_banla:'Hesap banı',cihaz_banla:'Cihaz banı',sohbet_sustur:'Sohbet susturma',sohbet_susturma_kaldir:'Susturma kaldırıldı',cihaz_bani_kaldir:'Cihaz banı kaldırıldı',odalardan_at:'Odalardan çıkarma',profil_temizle:'Profil temizliği',avatar_degistir:'Avatar değişikliği',uyari_gonder:'Kayıtlı uyarı',not_ekle:'Yönetici notu',oturumlari_sonlandir:'Oturumlar sonlandırıldı',platform_bani_kaldir:'Platform banı kaldırıldı',icerik_sil:'İçerik kaldırıldı'};
 const kinds={short:'Shorts',moment:'Gönderiler',short_comment:'Shorts yorumları',moment_comment:'Gönderi yorumları'};
 function buttons(ctx){const p=ctx.profile,c=ctx.caps;if(!(c.admin||c.sanction)||(p.muaf&&!c.owner)||p.id===ctx.user.id)return '<p class="note">Bu hesap için A/B işlemleri kapalı.</p>';
 const b=k=>`<button data-action="${k}" class="${['avatar','profile','note','warn'].includes(k)?'':'danger'}">${labels[k]}</button>`;
 return '<h3>Yaptırımlar</h3>'+b(p.banli?'unban':'ban')+['mute','unmute','warn','kick','closeRooms'].map(b).join('')+((c.super||c.owner)?['deviceBan','deviceUnban','logout'].map(b).join(''):'')+'<h3>Profil ve içerik</h3>'+['avatar','profile','note'].map(b).join('');
 }
 function input(name,label,extra=''){return `<label>${label}<input name="${name}" ${extra}></label>`;}
 async function action(kind,ctx){if(!labels[kind])return false;const {profile:p,caps:c,esc,rpc,toast,refresh,errorText,invoke}=ctx;
 if(!(c.admin||c.sanction)||(p.muaf&&!c.owner)||p.id===ctx.user.id||(['deviceBan','deviceUnban','logout'].includes(kind)&&!(c.super||c.owner)))return true;
 const field={ban:'<label>Ban süresi<select name="hours"><option value="24">1 gün</option><option value="72">3 gün</option><option value="168">7 gün</option><option value="720">30 gün</option><option value="0">Kalıcı</option></select></label>',mute:'<label>Susturma süresi<select name="minutes"><option value="15">15 dakika</option><option value="60">1 saat</option><option value="1440">1 gün</option><option value="4320">3 gün</option><option value="10080">7 gün</option><option value="43200">30 gün</option></select></label>',avatar:input('url','Yeni avatar adresi · boş bırakırsan kaldırılır','type="url" maxlength="2000" placeholder="Supabase room-images adresi"'),profile:'<fieldset><legend>Temizlenecek alanlar</legend><label class="check-line"><input type="checkbox" name="field" value="nickname"> Takma ad → Kullanıcı_ID</label><label class="check-line"><input type="checkbox" name="field" value="bio"> Bio</label><label class="check-line"><input type="checkbox" name="field" value="cover"> Fotoğraf galerisi (kapak kaynağı) ve video kapak</label></fieldset>'}[kind]||'';
 const textKind=['warn','note'].includes(kind),max=kind==='note'?4000:kind==='warn'?1000:300;
 const hint={unban:'Cihaz banları ayrıca kaldırılır.',deviceUnban:'Platform banı korunur. Paylaşılan cihazdaki diğer hesaplar etkilenebilir.',deviceBan:'Bu cihazdaki diğer hesaplar da erişimini kaybedebilir.',closeRooms:'Kullanıcı tüm odalardan çıkarılır; sahibi olduğu odalar kapatılır.',logout:'Aktif telefon oturumu çıkışa zorlanır, yenileme oturumları iptal edilir. Mevcut erişim tokenları süreleri dolana kadar geçerli kalabilir.',warn:'Uyarı sistem mesajı olarak kaydedilir ve push gönderimi denenir. Üçüncü uyarıda 24 saatlik ban önerilir.',note:'Bu not yalnız yetkili yöneticiler tarafından görülebilir.'}[kind]||'İşlem sebebi yönetim kütüğüne kaydedilir.';
 const dlg=document.createElement('dialog');dlg.className='phase2-dialog';dlg.setAttribute('aria-label',labels[kind]);dlg.innerHTML=`<form><div class="eyebrow">${textKind?'Kayıtlı iletişim':'Hesap işlemi'}</div><h2>${labels[kind]}</h2><p>${esc(p.nickname)} · ID ${esc(p.display_id)}<br><small>${esc(p.id)}</small></p><p class="note">${hint}</p>${field}<label>${textKind?'Metin':'İşlem sebebi'}<textarea name="reason" required minlength="3" maxlength="${max}"></textarea></label><div class="dialog-error" role="alert"></div><div class="dialog-actions"><button type="button" data-cancel>Vazgeç</button><button type="submit" class="primary">${textKind?'Kaydet ve gönder':'Onayla ve uygula'}</button></div></form>`;
 document.body.append(dlg);dlg.showModal();dlg.addEventListener('close',()=>dlg.remove());dlg.querySelector('[data-cancel]').onclick=()=>dlg.close();let busy=false,completed=null;const requestId=crypto.randomUUID();dlg.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
 dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.target),reason=String(f.get('reason')||'').trim(),err=dlg.querySelector('.dialog-error');if(reason.length<3){err.textContent='En az 3 karakter yaz.';return;}const fields=f.getAll('field');if(kind==='ban'&&(!f.has('hours')||!['0','24','72','168','720'].includes(String(f.get('hours'))))){err.textContent='Ban süresini seç.';return;}if(kind==='profile'&&!fields.length){err.textContent='En az bir alan seç.';return;}
 const args={p_user:p.id,p_neden:reason};const calls={ban:['yonetim_banla',{...args,p_hours:Number(f.get('hours'))}],unban:['yonetim_bani_kaldir',args],deviceBan:['yonetim_cihaz_banla',args],deviceUnban:['yonetim_cihaz_bani_kaldir',args],mute:['yonetim_sustur',{...args,p_dakika:Number(f.get('minutes'))}],unmute:['yonetim_susturma_kaldir',args],kick:['yonetim_odadan_at',{...args,p_odalarini_kapat:false}],closeRooms:['yonetim_odadan_at',{...args,p_odalarini_kapat:true}],avatar:['yonetim_avatar_degistir',{...args,p_url:String(f.get('url')||'').trim()||null}],profile:['yonetim_profil_temizle',{...args,p_alanlar:fields}],warn:['yonetim_uyari_gonder',{p_user:p.id,p_metin:reason,p_request_id:requestId}],note:['yonetim_not_ekle',{p_user:p.id,p_metin:reason,p_request_id:requestId}]};
 busy=true;dlg.querySelectorAll('button').forEach(b=>b.disabled=true);err.textContent='';
 try {const result=completed||(kind==='logout'?await invoke('admin-oturum-kapat',args):await rpc(...calls[kind]));completed=result;let message='İşlem kaydedildi.';
 if(kind==='warn'){try {const push=await invoke('admin-duyuru',{warning_id:result.warning_id});message=push.status==='no_device'?'Uyarı kaydedildi. Bildirim cihazı yok; push işlemi kapatıldı. Sistem mesajı hesabında mevcut.':push.delivered?'Uyarı kaydedildi, bildirim gönderildi.':'Uyarı kaydedildi. Sistem mesajı hesabında mevcut.';}catch(ex){message='Uyarı kaydedildi. '+errorText(ex)+' Sistem mesajı hesabında mevcut.';}if(result.ban_24h_suggested)message+=' Üç veya daha fazla uyarı: 24 saatlik banı değerlendir.';}
 dlg.close();toast(message);await refresh();
 }catch(ex){err.textContent=errorText(ex);busy=false;dlg.querySelectorAll('button').forEach(b=>b.disabled=false);}
 };return true;
 }
 async function renderTab(key,ctx){if(!tabs[key])return false;const {root,profile:p,rpc,esc,date,errorText,toast,refresh}=ctx;let page=0,type='short',serial=0;const selected=new Set();let rows=[];const limit=25;
 const pager=(total)=>`<div class="pager"><span>${total?`${page*limit+1}–${Math.min((page+1)*limit,total)} / ${total}`:'Kayıt yok'}</span><button data-prev ${page===0?'disabled':''}>Önceki</button><button data-next ${(page+1)*limit>=total?'disabled':''}>Sonraki</button></div>`;
 const bindPager=total=>{root.querySelector('[data-prev]').onclick=()=>{page--;selected.clear();load();};root.querySelector('[data-next]').onclick=()=>{page++;selected.clear();load();};};
 async function load(){const epoch=++serial;root.innerHTML='<div class="skeleton" role="status" aria-label="Yükleniyor"></div>';try {const d=await rpc({content:'yonetim_icerik_listesi',notes:'yonetim_notlar',audit:'yonetim_islem_gecmisi'}[key],{p_user:p.id,p_limit:limit,p_offset:page*limit,...(key==='content'?{p_tur:type}:{})});if(epoch!==serial||!root.isConnected)return;rows=d.rows||[];
 if(key==='content'){root.innerHTML=`<div class="content-toolbar"><label>İçerik türü<select data-type>${Object.entries(kinds).map(([v,l])=>`<option value="${v}" ${v===type?'selected':''}>${l}</option>`).join('')}</select></label><button class="danger" data-remove disabled>Seçilileri kaldır</button></div><p class="note">En fazla 50 kayıt. Medya temizliği güvenli dosya kuyruğundan yürür. Yarışma sonuçları korunur.</p><div class="content-list">${rows.length?rows.map(x=>`<article class="content-card"><label class="check-line"><input type="checkbox" data-select="${esc(x.id)}" ${x.protected||(p.muaf&&!ctx.caps.owner)?'disabled':''}><span>${esc(date(x.created_at))}</span></label><p>${esc(x.body||'Metinsiz içerik')}</p><small>${esc(x.status||'Yorum')} ${x.protected?'· Korunan yarışma sonucu':''}</small>${ctx.safeUrl(x.media_url)?`<a href="${esc(ctx.safeUrl(x.media_url))}" target="_blank" rel="noopener noreferrer">Medyayı aç ↗</a>`:''}</article>`).join(''):'<p class="empty-state">Bu türde içerik yok.</p>'}</div>${pager(d.total)}`;
 root.querySelector('[data-type]').onchange=e=>{type=e.target.value;page=0;selected.clear();load();};root.querySelectorAll('[data-select]').forEach(b=>b.onchange=()=>{b.checked?selected.add(b.dataset.select):selected.delete(b.dataset.select);const remove=root.querySelector('[data-remove]');remove.disabled=!selected.size;remove.textContent=selected.size?`${selected.size} kaydı kaldır`:'Seçilileri kaldır';});root.querySelector('[data-remove]').onclick=remove;
 }else if(key==='notes'){root.innerHTML=`<p class="note">Yalnız yetkili yöneticilerin görebildiği zaman damgalı notlar.</p>${rows.map(x=>`<article class="content-card"><small>${esc(date(x.created_at))} · ${esc(x.yazan_adi||x.yazan)}</small><p class="preserve-lines">${esc(x.metin)}</p></article>`).join('')||'<p class="empty-state">Yönetici notu yok.</p>'}${pager(d.total)}`;
 }else {root.innerHTML=`${rows.map(x=>`<article class="content-card"><small>${esc(date(x.created_at))}</small><strong>${esc(auditNames[x.action]||x.action)}</strong><p>${esc(x.actor_id||'Sistem')}</p><details><summary>Ayrıntı</summary><pre>${esc(JSON.stringify(x.detail,null,2))}</pre></details></article>`).join('')||'<p class="empty-state">İşlem kaydı yok.</p>'}${pager(d.total)}`;}bindPager(d.total);
 }catch(e){if(epoch!==serial||!root.isConnected)return;root.innerHTML=`<div class="empty-state"><p>${esc(errorText(e))}</p><button data-retry>Tekrar dene</button></div>`;root.querySelector('[data-retry]').onclick=load;}}
 function remove(){const ids=[...selected];if(!ids.length||ids.length>50)return;const dlg=document.createElement('dialog');dlg.innerHTML=`<form><h2>${ids.length} kayıt kaldırılacak</h2><p>${esc(p.nickname)} · ${kinds[type]}</p><p class="note">Seçili içerikler görünümden kaldırılır. Diğer kişilerin yorum yanıtları korunur.</p><label>İşlem sebebi<textarea name="reason" required minlength="3" maxlength="300"></textarea></label><div role="alert" class="dialog-error"></div><div class="dialog-actions"><button type="button">Vazgeç</button><button type="submit" class="danger">${ids.length} kaydı kaldır</button></div></form>`;document.body.append(dlg);dlg.showModal();dlg.addEventListener('close',()=>dlg.remove());let busy=false;dlg.querySelector('button[type=button]').onclick=()=>dlg.close();dlg.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const reason=String(new FormData(e.target).get('reason')||'').trim();if(reason.length<3)return;busy=true;dlg.querySelectorAll('button').forEach(b=>b.disabled=true);try {const d=await rpc('yonetim_icerik_sil',{p_tur:type,p_idler:ids,p_neden:reason});dlg.close();toast(`${d.removed} kayıt kaldırıldı.${d.cloudflare_retained?' Cloudflare dosyaları saklanıyor.':''}${d.storage_review?' '+d.storage_review+' dosyanın temizliği sahiplik incelemesi bekliyor.':''}`);selected.clear();load();}catch(ex){dlg.querySelector('.dialog-error').textContent=errorText(ex);busy=false;dlg.querySelectorAll('button').forEach(b=>b.disabled=false);}};}
 await load();return true;
 }
 async function renderStatus(ctx){const {root,profile:p,rpc,esc,date,errorText}=ctx;const box=document.createElement('section');box.className='moderation-status';root.append(box);box.innerHTML='<div class="skeleton" role="status" aria-label="Susturma ve uyarılar yükleniyor"></div>';try{const d=await rpc('yonetim_kullanici_durum',{p_user:p.id});if(!box.isConnected)return;box.innerHTML=`<h3>Sohbet susturması</h3>${d.mute?`<p class="danger-note">${esc(date(d.mute.expires_at))} tarihine kadar · ${esc(d.mute.reason)}</p>`:'<p class="note">Aktif sohbet susturması yok.</p>'}<h3>Kayıtlı uyarılar · ${esc(d.warning_count)}</h3>${d.warning_count>=3?'<p class="danger-note">Üç veya daha fazla uyarı var. 24 saatlik banı değerlendir.</p>':''}${(d.warnings||[]).map(x=>`<article class="content-card"><small>${esc(date(x.created_at))}</small><p class="preserve-lines">${esc(x.metin)}</p><small>${x.push_state==='no_device'?'Bildirim cihazı yok · push işlemi kapatıldı':x.push_sent_at?'Push gönderildi':'Sistem mesajı kaydedildi; push onayı yok'}</small></article>`).join('')||'<p class="note">Henüz uyarı yok.</p>'}`;}catch(e){if(box.isConnected)box.innerHTML=`<p class="note">Susturma ve uyarılar yüklenemedi: ${esc(errorText(e))}</p>`;}}
 window.PuffyPhase2={tabs,buttons,action,renderTab,renderStatus};
})();
