/* Puffy Faz 3: kullanıcı JWT'si; bütün yetki ve yazma kontrolleri sunucuda. */
(() => {
 'use strict';
 const labels={role:'Personel rolleri',displayId:'Sayısal ID değiştir',displayIdRestore:'ID\'yi geri al (asıl numara)',dealer:'Bayi durumu',specialId:'Katalogdan özel ID ver',specialIdRemove:'Özel ID kaldır',kycApprove:'KYC onayla',kycReject:'KYC reddet',agencyExit:'Ajanstan çıkar',familyExit:'Aileden çıkar',host:'Call Host ayarları',hostPhoto:'Call Host fotoğraf kararı',diamonds:'Elmas düzelt',freeze:'Para çekmeyi dondur / aç',vipAdjust:'Platform VIP kaldır / kısalt',vipRemoveAll:'VIP tamamen kaldır',deletion:'Hesap silme talebi'};
 const superKeys=['role','displayId','displayIdRestore','dealer','specialId','specialIdRemove','kycApprove','kycReject','agencyExit','familyExit','host','hostPhoto','deletion'];
 const ownerKeys=['diamonds','freeze','vipAdjust','vipRemoveAll'];
 const sections={gifts:'Hediyeler',rooms:'Odalar',reports:'Şikayetler',operations:'Hesap kontrolü',host:'Call Host',logins:'Giriş geçmişi',cash:'Kasa geçmişi'};
 function tabs(ctx){return Object.fromEntries(Object.entries(sections).filter(([k])=>!['operations','host','logins','cash'].includes(k)||(k==='cash'?ctx.caps.owner:ctx.caps.super||ctx.caps.owner)));}
 function allowed(key,ctx){return ctx.profile.id!==ctx.user.id&&(!ctx.profile.muaf||ctx.caps.owner)&&(ownerKeys.includes(key)?ctx.caps.owner:ctx.caps.super||ctx.caps.owner);}
 function buttons(ctx){return '<h3>Hesap yönetimi</h3>'+superKeys.filter(k=>allowed(k,ctx)).map(k=>`<button data-action="${k}">${labels[k]}</button>`).join('')+(ctx.caps.owner?'<h3>Kasa kontrolleri</h3>'+ownerKeys.filter(k=>allowed(k,ctx)).map(k=>`<button data-action="${k}">${labels[k]}</button>`).join(''):'');}
 const field=(name,label,attrs='')=>`<label>${label}<input name="${name}" ${attrs}></label>`;
 const choice=(name,label,values)=>`<label for="phase3-${name}">${label}</label><select id="phase3-${name}" name="${name}">${values.map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select>`;
 const bool=(name,label)=>choice(name,label,[['true','Evet'],['false','Hayır']]);
 async function action(key,ctx){if(!labels[key])return false;if(!allowed(key,ctx))return true;
  const {profile:p,esc,rpc,errorText,toast,refresh}=ctx;let d={};
  if(['specialId','agencyExit','familyExit','host','hostPhoto','deletion','vipAdjust'].includes(key)){
   try{d=key==='vipAdjust'?await rpc('yonetim_vip_paketleri',{p_user:p.id}):await rpc('yonetim_kullanici_ek',{p_user:p.id,p_bolum:['host','hostPhoto'].includes(key)?'host':'hesap'});}catch(e){toast(errorText(e));return true;}
  }
  if(key==='specialId'&&ctx.selectedCatalog)d.catalog=[ctx.selectedCatalog];
  const roles=ctx.roles||[];
  const options={role:[1,2,3].map(n=>choice('role'+n,n+'. rol',[['','Rol yok'],...roles.map(r=>[r,esc(ctx.roleName?.(r)||r)])])).join(''),displayId:field('id','Yeni sayısal ID','inputmode="numeric" pattern="[0-9]{4,6}" required')+'<p class="note">Kullanılabilir aralıklar: 1000–1999 veya 200000–299999.</p>',displayIdRestore:'<p class="note">Kullanıcı ve sahip olduğu oda, personel/özel numara verilmeden önceki ASIL numarasına döner; verilen numara boşa çıkar. Yedek kaydı yoksa işlem reddedilir.</p>',dealer:bool('enabled','Bayi hesabı'),specialId:choice('catalog_id','Katalogdaki uygun ID',(d.catalog||[]).map(x=>[esc(x.id),esc(x.vanity_id)+' · Seviye '+esc(x.required_level)]))+'<p class="note">İlk 25 uygun kayıt gösterilir. Hesap kontrolü sekmesinde katalog sayfalanabilir.</p>',agencyExit:choice('agency_id','Ajans',(d.agencies||[]).filter(x=>x.role!=='owner').map(x=>[esc(x.id),esc(x.name)])),familyExit:choice('family_id','Üyelik',(d.families||[]).filter(x=>x.role!=='owner').map(x=>[esc(x.family_id),esc(x.name)+' · '+esc(x.role)])),host:bool('approved','Call Host onaylı')+bool('open','Aramalara açık')+bool('audio','Sesli arama')+bool('video','Görüntülü arama')+field('label','Durum yazısı','maxlength="100"'),hostPhoto:bool('approved','Fotoğrafı onayla'),diamonds:field('amount','Elmas miktarı · azaltmak için eksi','type="number" min="-50000000" max="50000000" step="1" required')+field('password','Ödeme şifresi','type="password" required autocomplete="off"'),freeze:bool('frozen','Para çekme dondurulsun'),vipAdjust:choice('grant_id','Platform VIP paketi',(d.rows||[]).filter(x=>x.modifiable).map(x=>[esc(x.id),'VIP '+esc(x.tier)+' · '+esc(ctx.date(x.expires_at))]))+field('remaining','Kalan gün · kaldırmak için 0','type="number" min="0" max="365" step="1" value="0" required')+field('password','Ödeme şifresi','type="password" required autocomplete="off"')+'<p class="note">Satın alınmış veya birleşmiş paketler değiştirilmez.</p>',vipRemoveAll:'<p class="danger-note">Hesaptaki TÜM aktif VIP paketleri (satın alınmışlar dahil) hemen sona erer. Geri alınamaz; gerekirse sonra yeniden VIP verilir.</p>'+field('password','Ödeme şifresi','type="password" required autocomplete="off"'),deletion:choice('decision','Silme talebi kararı',[['onay','Onayla · mevcut 14 gün korunsun'],['reddet','Reddet · silme talebini kaldır'],['iptal','İptal · silme talebini kaldır']])+'<p class="note">Onay süreyi baştan başlatmaz ve hesabı hemen silmez.</p>'}[key]||'';
  if(['specialId','agencyExit','familyExit','vipAdjust'].includes(key)&&!options.includes('<option')){toast('Bu işlem için uygun kayıt yok.');return true;}
  if(['host','hostPhoto'].includes(key)&&!d.host){toast('Bu hesapta Call Host profili yok.');return true;}
  if(key==='deletion'&&!d.deletion_requested_at){toast('Bu hesapta aktif silme talebi yok.');return true;}
  const dlg=document.createElement('dialog');dlg.className='phase2-dialog';dlg.setAttribute('aria-label',labels[key]);dlg.innerHTML=`<form><div class="eyebrow">Hesap kontrolü</div><h2>${labels[key]}</h2><p>${esc(p.nickname)} · ID ${esc(p.display_id)}</p>${options}<label>İşlem sebebi<textarea name="reason" required minlength="${key==='agencyExit'?10:3}" maxlength="300"></textarea></label><p class="danger-note">Onayladığında işlem yönetim kütüğüne kaydedilir.</p><div class="dialog-error" role="alert"></div><div class="dialog-actions"><button type="button" data-cancel>Vazgeç</button><button type="submit" class="primary">Onayla ve uygula</button></div></form>`;document.body.append(dlg);dlg.showModal();dlg.addEventListener('close',()=>dlg.remove());dlg.querySelector('[data-cancel]').onclick=()=>dlg.close();let busy=false;const request=crypto.randomUUID();dlg.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
  if(key==='role')for(let n=1;n<=3;n++)dlg.querySelector(`[name=role${n}]`).value=p[n===1?'staff_role':'staff_role_'+n]||'';
  if(key==='dealer')dlg.querySelector('[name=enabled]').value=String(!!p.is_coin_dealer);
  if(key==='host'){for(const [name,column]of Object.entries({approved:'onayli',open:'acik',audio:'sesli_acik',video:'goruntulu_acik'}))dlg.querySelector(`[name=${name}]`).value=String(!!d.host[column]);dlg.querySelector('[name=label]').value=d.host.durum_yazisi||'';}
  dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.target),reason=String(f.get('reason')||'').trim(),err=dlg.querySelector('.dialog-error');if(reason.length<(key==='agencyExit'?10:3)){err.textContent='İşlem sebebini tamamla.';return;}const values=Object.fromEntries([...f].filter(([k])=>!['reason','password'].includes(k)));for(const k of ['role1','role2','role3'])if(values[k]==='')values[k]=null;
   if(key==='role'){const r=[values.role1,values.role2,values.role3].filter(Boolean);if(new Set(r).size!==r.length){err.textContent='Aynı rolü iki kez seçemezsin.';return;}}
   if(key==='displayId'){const id=Number(values.id);if(!Number.isInteger(id)||!((id>=1000&&id<=1999)||(id>=200000&&id<=299999))){err.textContent='ID, 1000–1999 veya 200000–299999 aralığında olmalı.';return;}}
   busy=true;dlg.querySelectorAll('button').forEach(b=>b.disabled=true);err.textContent='';
   try{let result;if(key==='diamonds'){const amount=Number(f.get('amount'));if(!Number.isSafeInteger(amount)||amount===0)throw new Error('INVALID_AMOUNT');result=await rpc('platform_elmas_islemi',{p_hedef:p.id,p_miktar:amount,p_neden:reason,p_odeme_sifresi:f.get('password'),p_request_id:request});}
    else if(key==='vipRemoveAll')result=await rpc('platform_vip_tamamen_kaldir',{p_hedef:p.id,p_neden:reason,p_odeme_sifresi:f.get('password'),p_request_id:request});
    else if(key==='vipAdjust')result=await rpc('platform_vip_kaldir',{p_hedef:p.id,p_neden:reason,p_odeme_sifresi:f.get('password'),p_grant:f.get('grant_id'),p_kalan_gun:Number(f.get('remaining')),p_request_id:request});
    else if(key==='deletion')result=await rpc('yonetim_hesap_silme_karar',{p_user:p.id,p_talep_at:d.deletion_requested_at,p_karar:f.get('decision'),p_neden:reason});
    else if(key==='agencyExit')result=await rpc('yonetim_ajanstan_cikar',{p_user:p.id,p_agency:f.get('agency_id'),p_neden:reason});
    else if(key==='freeze')result=await rpc('yonetim_para_cekme_dondur',{p_user:p.id,p_dondur:f.get('frozen')==='true',p_neden:reason});
    else if(key==='familyExit')result=await rpc('yonetim_aileden_cikar',{p_user:p.id,p_family:f.get('family_id'),p_neden:reason});
    else result=await rpc('yonetim_hesap_islemi',{p_user:p.id,p_islem:key,p_veri:values,p_neden:reason});
    if(result?.error||result?.ok===false)throw new Error(result?.error||'OPERATION_REJECTED');dlg.close();toast('İşlem kaydedildi.');await refresh();
   }catch(ex){err.textContent=errorText(ex);busy=false;dlg.querySelectorAll('button').forEach(b=>b.disabled=false);}
  };return true;
 }
 async function renderTab(key,ctx){if(!tabs(ctx)[key])return false;const {root,profile:p,rpc,invoke,esc,date,errorText}=ctx;let page=0,direction='gonderilen',cashType='coin',serial=0;const limit=25;
  const list=(rows,render)=>rows?.length?rows.map(x=>`<article class="content-card">${render(x)}</article>`).join(''):'<p class="empty-state">Kayıt bulunamadı.</p>';
  const pair=(label,value)=>`<div><dt>${esc(label)}</dt><dd>${esc(value??'—')}</dd></div>`;
  async function load(){const epoch=++serial;root.innerHTML='<div class="skeleton" role="status" aria-label="Yükleniyor"></div>';try{let d;if(key==='logins')d=await invoke('admin-giris-gecmisi',{p_user:p.id});else if(key==='cash')d=await rpc('yonetim_kasa_gecmisi',{p_user:p.id,p_tur:cashType,p_limit:limit,p_offset:page*limit});else d=await rpc('yonetim_kullanici_ek',{p_user:p.id,p_bolum:{gifts:'hediyeler',rooms:'odalar',reports:'sikayetler',operations:'hesap',host:'host'}[key],p_yon:direction,p_limit:limit,p_offset:page*limit});if(epoch!==serial||!root.isConnected)return;
   let html='';if(['gifts','reports'].includes(key))html+=choice('direction','Yön',[['gonderilen','Gönderilen'],['alinan','Alınan']]);if(key==='cash')html+=choice('cash-type','İşlem türü',[['coin','Coin'],['vip','VIP'],['elmas','Elmas']]);
   if(key==='operations')html+=`<dl class="key-values">${pair('E-posta',d.email||'Kayıt yok')}${pair('Telefon',d.phone||'Kayıt yok')}${pair('KYC',d.kyc?.verified?'Doğrulandı':'Doğrulanmadı')}${pair('KYC adı',d.kyc?.name)}${pair('Özel ID',d.special_id)}${pair('Silme talebi',date(d.deletion_requested_at))}${pair('Son silme kararı',d.deletion_decision)}</dl><button data-copy="phone">Telefonu kopyala</button><button data-copy="email">E-postayı kopyala</button><h3>Özel ID kataloğu</h3>`+list(d.catalog,x=>`<strong>${esc(x.vanity_id)}</strong><p>Seviye ${esc(x.required_level)}</p><button data-catalog="${esc(x.id)}" data-name="${esc(x.vanity_id)}" data-level="${esc(x.required_level)}">Bu ID’yi ver</button>`);
   if(key==='host')html+=d.host?`<dl class="key-values">${Object.entries(d.host).filter(([k])=>!k.includes('url')&&k!=='user_id').map(([k,v])=>pair({acik:'Açık',onayli:'Onaylı',sesli_acik:'Sesli',goruntulu_acik:'Görüntülü',durum_yazisi:'Durum',foto_red_sebebi:'Fotoğraf red sebebi',updated_at:'Güncellendi',onay_at:'Onay zamanı'}[k]||k,typeof v==='boolean'?(v?'Evet':'Hayır'):v)).join('')}</dl>`+(ctx.safeUrl(d.host.bekleyen_foto_url)?`<a href="${esc(ctx.safeUrl(d.host.bekleyen_foto_url))}" target="_blank" rel="noopener noreferrer">Bekleyen fotoğrafı aç ↗</a>`:''):'<p class="empty-state">Call Host profili yok.</p>';
   if(key==='gifts'){html+=`<div class="metrics"><div class="metric"><span>${direction==='gonderilen'?'Harcanan coin':'Coin bakiyesi hareketi'}</span><strong>${esc(d.extra?.coin_total??0)}</strong></div><div class="metric"><span>${direction==='alinan'?'Alınan elmas':'Elmas hareketi'}</span><strong>${esc(d.extra?.diamond_total??0)}</strong></div></div><h3>En çok hediye · ilk 5</h3>`+list(d.extra?.top,x=>`<strong>${esc(x.nickname)}</strong><p>${esc(x.quantity)} hediye</p>`)+`<p class="note">${esc(d.extra?.top_note)}</p>`+list(d.rows,x=>`<small>${esc(date(x.created_at))}</small><strong>${esc(x.type)}</strong><p>Coin ${esc(x.amount)} · Elmas ${esc(x.diamond_amount)}</p>`);}
   if(key==='rooms')html+='<h3>Sahibi olduğu odalar</h3>'+list(d.extra?.owned,x=>`<strong>${esc(x.name)}</strong><p>ID ${esc(x.display_id)} · ${x.is_active?'Açık':'Kapalı'}</p>`)+`<p class="note">${esc(d.extra?.broadcast_note)}</p><h3>Son 30 gün ziyaretleri</h3>`+list(d.rows,x=>`<strong>${esc(x.name)}</strong><p>${esc(date(x.visited_at))} · ID ${esc(x.display_id)}</p>`);
   if(key==='reports')html+=`<p class="note">${esc(d.extra?.resolution_note)}</p>`+list(d.rows,x=>`<small>${esc(date(x.created_at))} · ${esc(x.content_type)}</small><p>${esc(x.reason)}</p><small>Karar: ${esc(x.resolution||'Kayıtta belirtilmemiş')}</small>`);
   if(key==='logins')html+=`<p class="note">${esc(d.note)}</p>`+list(d.rows,x=>`<small>${esc(date(x.created_at))}</small><strong>${esc(x.action)}</strong><p>IP ${esc(x.ip_masked||'Kayıt yok')}</p>`);
   if(key==='cash')html+=(p.id?`<p class="note">Para çekme: ${d.freeze?.frozen?'Donduruldu':'Açık'} · ${esc(d.freeze?.reason||'')}</p>`:'')+list(d.rows,x=>{/* F02: kim, kime, hangi yön, önce/sonra */const coin=cashType==='coin';const geri=x.yon==='geri_cek';const isaret=coin?(geri?'−':'+'):'';const yonAd=coin?(x.geri_alma?'Geri alma':geri?'Geri çekme':x.satis_usd!=null?'Satış':'Gönderme'):'';const kim=x.sahip_ad?`${esc(x.sahip_ad)}${x.sahip_display_id?' · ID '+esc(x.sahip_display_id):''}`:'';const kime=x.hedef_ad?`<a href="#kullanici/${esc(x.hedef_id)}">${esc(x.hedef_ad)}</a>${x.hedef_display_id?' · ID '+esc(x.hedef_display_id):''}`:(x.hedef_id?`<a href="#kullanici/${esc(x.hedef_id)}">${esc(x.hedef_id)}</a>`:'');const bakiye=(x.onceki_bakiye!=null&&x.sonraki_bakiye!=null)?`${Number(x.onceki_bakiye).toLocaleString('tr-TR')} → ${Number(x.sonraki_bakiye).toLocaleString('tr-TR')}`:'';return `<small>${esc(date(x.created_at))}${coin?` · ${esc(yonAd)}${x.hesap?' · '+esc(x.hesap):''}${x.geri_alindi?' · <b>geri alındı</b>':''}`:''}</small><strong>${coin?`<span style="color:${geri?'#d9534f':'#2e9e5b'}">${isaret}${Number(x.miktar).toLocaleString('tr-TR')}</span>${x.satis_usd!=null?` <small>(${Number(x.satis_usd).toLocaleString('tr-TR')} $)</small>`:''}`:esc(x.miktar??('VIP '+x.tier+' · '+x.gun+' gün'))}</strong>${coin?`<p>${kime?'Hedef: '+kime:''}${kim?' · Yapan: '+kim:''}${bakiye?' · Bakiye: '+bakiye:''}</p>`:''}<p>${x.action?esc(x.action)+' · ':''}${esc(x.neden||'')}${x.id?` <small class="muted">#${esc(String(x.id).slice(0,8))}</small>`:''}</p>`;});
   const total=key==='operations'?d.catalog_total:d.total;if(total!=null)html+=`<div class="pager"><span>${esc(total)} kayıt</span><button data-prev ${page===0?'disabled':''}>Önceki</button><button data-next ${(page+1)*limit>=total?'disabled':''}>Sonraki</button></div>`;root.innerHTML=html;
   root.querySelector('[data-prev]')?.addEventListener('click',()=>{page--;load();});root.querySelector('[data-next]')?.addEventListener('click',()=>{page++;load();});for(const [name,value] of [['direction',direction],['cash-type',cashType]]){const select=root.querySelector(`[name="${name}"]`);if(select){select.value=value;select.onchange=()=>{name==='direction'?direction=select.value:cashType=select.value;page=0;load();};}}
   root.querySelectorAll('[data-copy]').forEach(b=>{const value=d[b.dataset.copy];b.disabled=!value;b.onclick=async()=>{try{await navigator.clipboard.writeText(value);ctx.toast('Kopyalandı.');}catch(_){ctx.toast('Kopyalanamadı; değeri seçerek kopyalayabilirsin.');}};});
   root.querySelectorAll('[data-catalog]').forEach(b=>b.onclick=()=>catalogAction({id:b.dataset.catalog,vanity_id:b.dataset.name,required_level:b.dataset.level},ctx));
  }catch(e){if(epoch===serial&&root.isConnected){root.innerHTML=`<p class="empty-state">${esc(errorText(e))}</p><button data-retry>Tekrar dene</button>`;root.querySelector('[data-retry]').onclick=load;}}}
  load();return true;
 }
 async function catalogAction(item,ctx){return action('specialId',{...ctx,selectedCatalog:item});}
 window.PuffyPhase3={tabs,buttons,action,renderTab};
})();
