/* Puffy Yönetim, Faz 1. Tüm yazma işlemleri mevcut RPC'lerden geçer. */
(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num = n => n == null ? '—' : new Intl.NumberFormat('tr-TR',{maximumFractionDigits:2}).format(Number(n));
  const date = s => s ? new Date(s).toLocaleString('tr-TR',{dateStyle:'medium',timeStyle:'short'}) : '—';
  const ledgerName = x => ({purchase:'Satın alma',spend:'Harcama',gift_sent:'Hediye gönderimi',gift_received:'Hediye kazancı',gift_sent_bag:'Çantadan hediye',lucky_gift_stake:'Şanslı hediye',lucky_gift_payout:'Şanslı hediye kazancı',platform_grant:'Platformdan coin',platform_clawback:'Platform geri çekimi',dealer_sale_in:'Bayi satışı',refund:'İade',chargeback_clawback:'Ödeme itirazı',system_grant:'Sistem ödülü',diamond_conversion:'Elmas dönüşümü'}[x]||x);
  const purchaseState = x => ({pending:'Bekliyor',verified:'Doğrulandı',granted:'Tamamlandı',refunded:'İade edildi',failed:'Başarısız'}[x]||x);
  const roles = ['super_admin','manager','admin','official','customer_service','sunucu','bd','asistan'];
  const roleName = r => ({super_admin:'Super Admin',manager:'Manager',admin:'Admin',official:'Official',customer_service:'Müşteri hizmetleri',sunucu:'Sunucu',bd:'BD',asistan:'Asistan'}[r] || r);
  const state = {sb:null,user:null,caps:{},epoch:0,page:0,limit:25,days:7,query:'',directId:false,filters:{},detail:null,tab:'transactions',chart:null,route:'',toast:null};
  const errorText = error => {
    const message = error?.message || String(error);
    const map = {MFA_REQUIRED:'Güvenlik doğrulamanı yenilemek için yeniden giriş yap.',NOT_AUTHORIZED:'Bu işlem için yetkin yok.',UNAUTHORIZED:'Bu işlem için yetkin yok.',NOT_ALLOWED:'Bu işlem için yetkin yok.',TARGET_NOT_FOUND:'Bu hesap artık mevcut değil.',INVALID_ROLE:'Aynı rolü iki kez seçemezsin.',PERSONEL_MUAF:'Personel hesabına bu yaptırım uygulanamaz.',INVALID_TARGET:'Kendi hesabına bu işlemi uygulayamazsın.',INVALID_DURATION:'Susturma süresi 1 dakika–30 gün arasında olmalı.',INVALID_BAN_DURATION:'Ban için 1, 3, 7, 30 gün veya kalıcı seç.',ALREADY_REVIEWED:'Kayıt başka bir yönetici tarafından sonuçlandırılmış.',PAYMENT_PASSWORD:'Ödeme şifresi doğrulanamadı.',INVALID_REASON:'İşlem sebebini kontrol et.',TARGET_NOT_FOUND:'Hesap bulunamadı.',CONTENT_NOT_FOUND:'İçerik değişmiş olabilir; listeyi yenile.',CONTENT_PROTECTED:'Yarışma sonucu korunur, kaldırılamaz.',ALREADY_REMOVED:'İçerik zaten kaldırılmış; listeyi yenile.',SHARED_STAFF_DEVICE:'Bu cihaz personel hesabıyla paylaşılıyor; işlem durduruldu.',INVALID_FIELDS:'Temizlenecek alanları seç.',INVALID_URL:'Avatar için uygulamanın room-images Storage adresini kullan.',IDEMPOTENCY_CONFLICT:'Bu istek farklı içerikle tekrar kullanılamaz.',NOT_AUTHENTICATED:'Oturumun sona erdi; yeniden giriş yap.',INVALID_REQUEST:'Metni veya istek alanlarını kontrol et.',INVALID_BATCH:'1–50 kayıt seç.',INVALID_TYPE:'Geçerli bir içerik türü seç.',PUSH_BUSY:'Bildirim başka bir gönderim tarafından işleniyor.',PUSH_EVENT_MISSING:'Uyarının bildirim kaydı eksik; yönetici denetimi gerekiyor.',PUSH_SECRET_UNAVAILABLE:'Push köprüsünün sunucu yapılandırması eksik.',PUSH_NOT_CONFIGURED:'Bildirim servisi yapılandırılmamış.',PUSH_DELIVERY_FAILED:'Bildirim servisi isteği tamamlayamadı.',PUSH_ACK_FAILED:'Bildirim sonucu kaydedilemedi; gönderim durumu denetlenmeli.',INVALID_PUSH_STATUS:'Bildirim durum kaydı geçersiz.'};
    if(error?.code==='PGRST202' || message.includes('Could not find the function')) return 'Bu ekranın veri bağlantısı hazırlanıyor. Sunucu güncellemesi tamamlandıktan sonra tekrar dene.';
    return Object.entries(map).find(([key])=>message.includes(key))?.[1] || 'İşlem tamamlanamadı. Bağlantını kontrol edip tekrar dene.';
  };
  const toast = message => { const el=$('#toast'); el.textContent=message; el.classList.add('acik'); clearTimeout(state.toast); state.toast=setTimeout(()=>el.classList.remove('acik'),4000); };
  async function rpc(name,params={}) { const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);try{const request=state.sb.rpc(name,params);const r=await (typeof request.abortSignal==='function'?request.abortSignal(controller.signal):request);if(r.error)throw r.error;return r.data;}finally{clearTimeout(timer);} }
  function safeUrl(url) { if(typeof url!=='string'||!url.trim())return '';try { const u=new URL(url,location.href); return ['https:','http:'].includes(u.protocol)?u.href:''; } catch{return '';} }
  function avatar(p) { const url=safeUrl(p.avatar_url); return url ? `<img src="${esc(url)}" alt="" loading="lazy" referrerpolicy="no-referrer">` : `<span class="initial-avatar" aria-hidden="true">${esc((p.nickname||'?').slice(0,1))}</span>`; }
  function bindAvatars(root) { root.querySelectorAll('.person img,.identity img').forEach(img=>img.addEventListener('error',()=>{ const s=document.createElement('span'); s.className='initial-avatar'; s.textContent='?'; img.replaceWith(s); },{once:true})); }
  const badges = p => `${p.banli?'<span class="tag bad">Banlı</span>':'<span class="tag good">Aktif</span>'}${p.vip_tier?`<span class="tag copper">VIP ${esc(p.vip_tier)}</span>`:''}${[p.staff_role,p.staff_role_2,p.staff_role_3].filter(Boolean).map(r=>`<span class="tag">${esc(roleName(r))}</span>`).join('')}`;
  function pending(root,error,retry) { root.innerHTML=`<div class="empty-state"><strong>Veri alınamadı</strong><div>${esc(errorText(error))}</div><button type="button">Tekrar dene</button></div>`; root.querySelector('button').onclick=retry; }
  function skeleton(root) { root.innerHTML='<div class="skeleton" role="status" aria-label="Yükleniyor"></div><div class="skeleton"></div>'; }
  function title(eyebrow,name,description,controls='') { return `<div class="page-title"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(name)}</h1><p>${esc(description)}</p></div>${controls}</div>`; }
  async function authorize(sb,user) {
    const calls=[['admin','platform_admini_miyim',{}],['moderator','is_platform_moderator',{p_uid:user.id}],['agency','ajans_onaycisi_miyim',{}],['owner','platform_sahibi_miyim',{}],['super','is_super_admin',{p_user:user.id}],['sanction','yaptirim_yetkisi',{p_uid:user.id}]];
    const values=await Promise.all(calls.map(async([key,name,args])=>{const r=await sb.rpc(name,args);return [key,!r.error && r.data===true];}));
    const caps=Object.fromEntries(values); return {allowed:caps.admin||caps.moderator||caps.agency,caps};
  }
  function open({sb,user,caps}) {
    state.sb=sb;state.user=user;state.caps=caps;state.epoch++;
    $('#kim').textContent=(caps.owner?'Platform sahibi':caps.admin?'Platform yöneticisi':caps.moderator?'Official':'Ajans onaycısı')+' · '+(user.email||'');
    document.querySelectorAll('[data-sayfa]').forEach(a=>{const key=a.dataset.sayfa;a.hidden=key==='kullanici'?!(caps.admin||caps.sanction):key==='personel'?!caps.admin:key==='shorts'?!caps.admin:key==='sikayet'?!caps.moderator:false;});
    const top=$('#panel-topbar'); if(!top.childElementCount) {
      top.innerHTML='<button class="mobile-menu" aria-label="Menüyü aç" aria-expanded="false">☰</button><span class="breadcrumb">Puffy / <b id="route-name">Genel bakış</b></span><form id="global-search"><label class="sr-only" for="global-query">Kullanıcı adı veya ID</label><input id="global-query" maxlength="100" placeholder="Kullanıcı adı veya ID"><button type="submit" aria-label="Kullanıcı ara">Ara</button></form><span class="session-tag">● Güvenli oturum</span>';
      top.querySelector('.mobile-menu').onclick=()=>{const visible=$('#uyg nav').classList.toggle('open');top.querySelector('.mobile-menu').setAttribute('aria-expanded',String(visible));};
      $('#global-search').onsubmit=e=>{e.preventDefault();state.query=$('#global-query').value.trim();state.filters={};state.directId=/^[0-9]+$/.test(state.query);state.page=0;location.hash='kullanici'; if(state.route==='kullanici') users();};
    }
    $('#global-search').hidden=!(caps.admin||caps.sanction);$('#close-menu').onclick=()=>{$('#uyg nav').classList.remove('open');$('#panel-topbar .mobile-menu').setAttribute('aria-expanded','false');};
  }
  function close() { state.epoch++;state.user=null;state.detail=null;state.route='';state.chart?.destroy();state.chart=null;$('#s-kullanici').replaceChildren();$('#s-personel').replaceChildren();$('#s-ozet').replaceChildren();document.querySelector('dialog')?.close(); }
  function route(hash) {
    const [page,id]=hash.split('/'); if(!['ozet','kullanici','personel'].includes(page)) {state.epoch++;state.route=page;return false;}
    if(!state.user)return true;
    if((page==='kullanici'&&!(state.caps.admin||state.caps.sanction))||(page==='personel'&&!state.caps.admin)){toast('Bu bölüm için yetkin yok.');location.hash='ozet';return true;}
    document.querySelectorAll('dialog').forEach(d=>d.close());state.epoch++;state.route=hash;$('#uyg nav').classList.remove('open');$('#panel-topbar .mobile-menu')?.setAttribute('aria-expanded','false');
    document.querySelectorAll('.workspace > [id^="s-"]').forEach(el=>el.classList.toggle('hidden',el.id!=='s-'+page));
    document.querySelectorAll('nav a.menu').forEach(a=>a.classList.toggle('aktif',a.dataset.sayfa===page));
    $('#route-name').textContent={ozet:'Genel bakış',kullanici:id?'Kullanıcı ayrıntısı':'Kullanıcılar',personel:'Personel ve yetki'}[page];
    if(page==='ozet')overview();else if(page==='personel')staff();else if(id)detail(id);else users();return true;
  }
  async function overview() {
    const root=$('#s-ozet'),epoch=++state.epoch;
    root.innerHTML=title('Operasyon merkezi','Platformun nabzı','Öncelikli kararlar ve dönem içindeki hareketler.',`<div class="periods">${[1,7,30].map(d=>`<button data-days="${d}" class="${state.days===d?'active':''}">${d===1?'Bugün':d+' gün'}</button>`).join('')}<button id="overview-refresh" aria-label="Göstergeleri yenile">↻</button></div>`)+'<div id="stats-content"></div><div class="grid-two"><section class="panel"><div class="panel-head"><h2>Karar bekleyenler</h2></div><div id="pending-content"></div></section><section class="panel"><div class="panel-head"><h2>Sürüm dağılımı</h2></div><div id="version-content"></div></section></div><section class="panel" id="recent-reports"></section>';
    root.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>{state.days=Number(b.dataset.days);overview();});$('#overview-refresh').onclick=overview;
    const boxes=[$('#stats-content'),$('#pending-content'),$('#version-content'),$('#recent-reports')];boxes.forEach(skeleton);
    const tasks=[state.caps.admin?rpc('admin_istatistik',{p_gun:state.days}):Promise.resolve(null),state.caps.admin?rpc('onay_bekleyenler'):Promise.resolve(null),state.caps.admin?rpc('admin_surum_dagilimi'):Promise.resolve(null),state.caps.moderator?rpc('moderator_sikayet_kuyrugu',{p_tur:'kullanici',p_limit:5,p_offset:0}):Promise.resolve(null)];
    const results=await Promise.allSettled(tasks); if(epoch!==state.epoch)return;
    results.forEach((r,i)=>{if(r.status==='rejected')pending(boxes[i],r.reason,overview);});
    if(results[0].status==='fulfilled') {
      const d=results[0].value;
      if(!d)boxes[0].innerHTML='<div class="alert">Yetkili olduğun işlemlere sol menüden ulaşabilirsin. Platform istatistikleri platform yöneticilerine açıktır.</div>';
      else {const s=d.summary; boxes[0].innerHTML=`<div class="metrics">${[['Yeni hesap',s.registrations,'Dönem içinde kayıt olanlar'],['Aktif hesap',s.active_users,'Son görülmesi dönem içinde olanlar'],['Coin satışı',s.sales_try,'TRY · tamamlanan satın almalar'],['Satılan coin',s.sales_coins,'Olay kaydındaki coin miktarı'],['Harcanan coin',s.spent_coins,'Hediye ve harcama işlemleri'],['Hediye hacmi',s.gift_coins,'Coin ile gönderilen hediyeler'],['Canlı oda',s.active_rooms,'Son 150 saniyede varlık sinyali'],['Yayın saati',s.broadcast_hours,'Süre kaydı doğrulanmayı bekliyor']].map(([l,n,h])=>`<div class="metric ${l.includes('coin')||l==='Coin satışı'?'coin':''}"><span>${l}</span><strong>${num(n)}</strong><small>${h}</small></div>`).join('')}</div><section class="panel"><div class="panel-head"><h2>Satış ve kayıt akışı</h2><span class="muted">${state.days} günlük görünüm</span></div><div class="chart-box"><canvas id="activity-chart" aria-label="Günlük satın alma tutarı ve yeni hesap sayısı" role="img"></canvas></div><details class="note"><summary>Grafiğin verilerini göster</summary>${table(['Gün','Satış · TRY','Yeni hesap'],d.series.map(x=>[esc(x.day),num(x.sales_try),num(x.registrations)]))}</details></section><p class="note">Veri zamanı: ${esc(date(d.as_of))} · Europe/Istanbul. Satış tutarı iade sonrası net gelir değildir.${Number(s.unpriced_purchases)>0?` ${num(s.unpriced_purchases)} satın alma kaydında fiyat eksik; tutara eklenmedi.`:''}</p>`;
        state.chart?.destroy(); if(window.Chart)state.chart=new Chart($('#activity-chart'),{type:'line',data:{labels:d.series.map(x=>new Date(x.day).toLocaleDateString('tr-TR',{day:'numeric',month:'short'})),datasets:[{label:'Satış · TRY',data:d.series.map(x=>x.sales_try),borderColor:'#e89157',backgroundColor:'#e8915710',fill:true,tension:.25,yAxisID:'y'},{label:'Yeni hesap',data:d.series.map(x=>x.registrations),borderColor:'#82c8a3',tension:.25,yAxisID:'y1'}]},options:{animation:!matchMedia('(prefers-reduced-motion: reduce)').matches,responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{color:'#a9a697',boxWidth:12}}},scales:{x:{ticks:{color:'#a9a697'},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#a9a697'},grid:{color:'#ffffff08'}},y1:{position:'right',beginAtZero:true,ticks:{color:'#82c8a3',precision:0},grid:{drawOnChartArea:false}}}}});else $('#activity-chart').replaceWith(Object.assign(document.createElement('p'),{textContent:'Grafik yüklenemedi; tüm değerler yukarıdaki veri tablosunda mevcut.'}));
      }
    }
    if(results[1].status==='fulfilled') {const d=results[1].value;const labels={short:'Shorts',sikayet:'Şikâyet',ajans_kurma:'Ajans kurma',ajans_logo:'Ajans logosu',etkinlik:'Etkinlik',oda_kapagi:'Oda kapağı',oda_temasi:'Oda teması',bayi_yukleme:'Bayi yükleme',para_cekme:'Para çekme'}; boxes[1].innerHTML=d?Object.entries(labels).map(([key,label])=>`<div class="queue-row"><span>${key==='short'&&state.caps.admin?`<a href="#shorts">${label} →</a>`:key==='sikayet'&&state.caps.moderator?`<a href="#sikayet">${label} →</a>`:label}</span><b>${num(d[key]??0)}</b></div>`).join('')+'<p class="note">Diğer onay ekranları sonraki fazlarda bağlanacak.</p>':'<p class="muted">Genel sayaçlar platform yöneticilerine açık.</p>';}
    if(results[2].status==='fulfilled'){const rows=results[2].value?.surumler;boxes[2].innerHTML=rows?.length?rows.map(x=>`<div class="version-row"><span>${esc(x.surum)} <small class="muted">${esc(x.platform)}</small></span><b>${num(x.kisi)} kişi</b></div>`).join(''):'<p class="muted">Gösterilecek sürüm kaydı yok veya bu bölüm için yetkin yok.</p>';}
    if(results[3].status==='fulfilled'){const rows=results[3].value;boxes[3].innerHTML='<div class="panel-head"><h2>Son kullanıcı şikâyetleri</h2></div>'+(rows?.length?table(['Hedef','Sebep','Tarih'],rows.map(x=>[state.caps.admin?`<a href="#kullanici/${esc(x.hedef_id)}">${esc(x.hedef_ad||'—')}</a>`:esc(x.hedef_ad||'—'),`<span class="tag ${x.sebep==='child_safety'?'bad':''}">${esc(x.sebep)}</span>`,esc(date(x.olusturuldu))])):'<p class="muted">Gösterilecek şikâyet yok veya bu bölüm için yetkin yok.</p>');}
  }
  function table(headers,rows) { return rows.length?`<div class="table-wrap"><table class="data-table responsive"><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map((x,i)=>`<td data-label="${esc(headers[i])}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">Bu bölümde kayıt yok.</div>'; }
  async function users() {
    const root=$('#s-kullanici'),epoch=++state.epoch,directId=state.directId; state.directId=false;state.detail=null;
    root.innerHTML=title('Hesap yönetimi','Kullanıcılar','Hesabı bul, geçmişini incele ve yetkili işlemleri uygula.')+`<form class="filters" id="user-filters"><label class="sr-only" for="user-query">Kullanıcı adı, ID veya UUID</label><input id="user-query" maxlength="100" placeholder="Ad, ID veya UUID" value="${esc(state.query)}"><label class="sr-only" for="status-filter">Hesap durumu</label><select id="status-filter"><option value="">Tüm durumlar</option><option value="aktif">Aktif</option><option value="banli">Banlı</option><option value="silme">Silme talebi</option></select><label class="sr-only" for="vip-filter">VIP durumu</label><select id="vip-filter"><option value="">Tüm VIP durumları</option><option value="var">VIP var</option><option value="yok">VIP yok</option></select><label class="sr-only" for="role-filter">Personel rolü</label><select id="role-filter"><option value="">Tüm roller</option>${roles.map(r=>`<option value="${r}">${roleName(r)}</option>`).join('')}</select><label class="sr-only" for="country-filter">Ülke</label><input id="country-filter" maxlength="80" placeholder="Ülke" value="${esc(state.filters.ulke||'')}"><button class="primary">Ara</button><button type="button" id="clear-filters">Sıfırla</button></form><div class="panel" id="user-results"></div>`;
    $('#status-filter').value=state.filters.durum||'';$('#vip-filter').value=state.filters.vip||'';$('#role-filter').value=state.filters.rol||'';
    $('#user-filters').onsubmit=e=>{e.preventDefault();state.query=$('#user-query').value.trim();state.filters={durum:$('#status-filter').value,vip:$('#vip-filter').value,rol:$('#role-filter').value,ulke:$('#country-filter').value.trim()};state.page=0;users();};
    $('#clear-filters').onclick=()=>{state.query='';state.filters={};state.page=0;users();};const target=$('#user-results');skeleton(target);
    try {const d=await rpc('admin_kullanici_listesi',{p_arama:state.query,p_filtre:state.filters,p_limit:state.limit,p_offset:state.page*state.limit});if(epoch!==state.epoch)return;
      if(directId&&d.total===1&&d.rows.length===1&&String(d.rows[0].display_id)===state.query){location.hash='kullanici/'+d.rows[0].id;return;}
      if(!d.rows.length&&state.page>0){state.page=Math.max(0,Math.ceil(d.total/state.limit)-1);return users();}
      target.innerHTML=d.rows.length?`<div class="table-wrap"><table class="data-table responsive"><thead><tr><th>Kullanıcı</th><th>Durum ve rol</th><th>Ülke</th><th>Son görülme</th><th>Kayıt</th></tr></thead><tbody>${d.rows.map(p=>`<tr class="user-row" tabindex="0" role="link" aria-label="${esc(p.nickname)} · ID ${esc(p.display_id||'—')} · Hesabı aç" data-user-id="${esc(p.id)}"><td><div class="person">${avatar(p)}<div><a href="#kullanici/${esc(p.id)}">${esc(p.nickname)}</a><small>ID ${esc(p.display_id||'—')}</small></div></div></td><td data-label="Durum">${badges(p)}</td><td data-label="Ülke">${esc(p.country||'—')}</td><td data-label="Son görülme">${esc(date(p.last_seen_at))}</td><td data-label="Kayıt">${esc(date(p.created_at))}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state"><strong>Kullanıcı bulunamadı</strong>Arama veya filtrelerini değiştir.</div>';
      target.innerHTML+=`<div class="pagination"><span>${num(d.total)} hesap · ${d.total?num(state.page*state.limit+1):0}–${num(Math.min((state.page+1)*state.limit,d.total))} gösteriliyor</span><div class="buttons"><button id="previous-page" ${state.page===0?'disabled':''}>← Önceki</button><button id="next-page" ${(state.page+1)*state.limit>=d.total?'disabled':''}>Sonraki →</button></div></div>`;
      $('#previous-page').onclick=()=>{state.page--;users();};$('#next-page').onclick=()=>{state.page++;users();};bindAvatars(target);target.querySelectorAll('[data-user-id]').forEach(row=>{row.onclick=e=>{if(e.target.closest('a,button')||window.getSelection()?.toString())return;if(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;location.hash='kullanici/'+row.dataset.userId;};row.onkeydown=e=>{if(e.target===row&&(e.key==='Enter'||e.key===' ')){e.preventDefault();location.hash='kullanici/'+row.dataset.userId;}};});
    }catch(e){if(epoch===state.epoch)pending(target,e,users);}
  }
  async function detail(id) {
    const root=$('#s-kullanici'),epoch=++state.epoch;state.detail=null;skeleton(root);
    if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)){root.innerHTML='<div class="alert error">Geçerli bir kullanıcı seç.</div><a href="#kullanici">Kullanıcılara dön</a>';return;}
    try {const d=await rpc('admin_kullanici_detay',{p_user:id});if(epoch!==state.epoch)return;state.detail=d;renderDetail();}catch(e){if(epoch===state.epoch)pending(root,e,()=>detail(id));}
  }
  function renderDetail() {
    const d=state.detail,p=d.profile,root=$('#s-kullanici');
    const tabs={transactions:'Cüzdan',purchases:'Satın almalar',account:'Hesap',devices:'Cihazlar',moderation:'Yaptırımlar',...(window.PuffyPhase2?.tabs||{})};
    root.innerHTML=`<div class="page-title"><a href="#kullanici">← Kullanıcılara dön</a><button id="detail-refresh">Yenile</button></div><div class="detail-mobile-actions"><span>Hesap işlemleri</span><button id="mobile-actions" class="primary" aria-haspopup="dialog">İşlemler <span aria-hidden="true">↗</span></button></div><div class="detail-layout"><div><section class="panel"><div class="identity">${avatar(p)}<div><h1>${esc(p.nickname)}</h1><p>ID ${esc(p.display_id||'—')} · ${esc(p.country||'Ülke belirtilmemiş')}</p>${badges(p)}</div></div><div class="metrics">${[['Coin',d.wallet?.coin_balance],['Elmas',d.wallet?.diamond_balance],['Bayi stoku',d.dealer_balance],['Şikâyet',d.report_count]].map(([l,n])=>`<div class="metric"><span>${l}</span><strong>${num(n)}</strong></div>`).join('')}</div><div class="detail-tabs" role="tablist">${Object.entries(tabs).map(([key,label])=>`<button role="tab" id="detail-tab-${key}" tabindex="${key===state.tab?0:-1}" aria-selected="${key===state.tab}" aria-controls="detail-content" data-tab="${key}" class="${key===state.tab?'active':''}">${label}</button>`).join('')}</div><div id="detail-content" role="tabpanel" aria-labelledby="detail-tab-${state.tab}"></div></section><p class="note">Veri zamanı: ${esc(date(d.as_of))}. Cüzdan, satın alma ve kütükte en son 50 kayıt gösterilir. Tam ban geçmişi işlem kütüğündedir.</p></div><aside class="panel action-list" aria-label="Hesap işlemleri">${window.PuffyPhase2?.buttons(phase2Context())||''}<h3>Hesap yönetimi</h3>${state.caps.admin?'<button data-action="role">Personel rolleri</button><button data-action="displayId">Özel ID</button><button data-action="dealer">Bayi durumunu değiştir</button>':''}${state.caps.super?'<button data-action="kyc">KYC doğrulaması</button>':''}${state.caps.owner?'<h3>Platform sahibi kasası</h3><button data-action="grant">Coin gönder</button><button data-action="clawback">Coin geri çek</button><button data-action="vip">VIP paketi ver</button><button data-action="ownerHistory">Kasa işlem geçmişi</button>':''}<p class="note">İşlem sonuçları sunucu tarafından doğrulanır. Coin/VIP için ödeme şifren gerekir.</p></aside></div>`;
    $('#detail-refresh').onclick=()=>detail(p.id);root.querySelectorAll('[data-tab]').forEach(b=>{b.onclick=()=>{state.tab=b.dataset.tab;renderDetail();$('#detail-tab-'+state.tab).focus();};b.onkeydown=e=>{const keys=Object.keys(tabs);let i=keys.indexOf(state.tab);if(e.key==='ArrowRight')i=(i+1)%keys.length;else if(e.key==='ArrowLeft')i=(i+keys.length-1)%keys.length;else if(e.key==='Home')i=0;else if(e.key==='End')i=keys.length-1;else return;e.preventDefault();state.tab=keys[i];renderDetail();$('#detail-tab-'+state.tab).focus();};});$('#mobile-actions').onclick=openActionSheet;root.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{document.querySelector('.actions-sheet')?.close();action(b.dataset.action);});bindAvatars(root);
    const c=$('#detail-content');
    if(window.PuffyPhase2?.tabs[state.tab])window.PuffyPhase2.renderTab(state.tab,{...phase2Context(),root:c});
    if(state.tab==='transactions')c.innerHTML=table(['Zaman','Tür','Coin','Elmas','Referans'],d.transactions.map(x=>[esc(date(x.created_at)),esc(ledgerName(x.type)),num(x.amount),num(x.diamond_amount),esc(x.reference||'—')]));
    if(state.tab==='purchases')c.innerHTML=table(['Zaman','Ürün','Platform','Coin','TRY','Durum'],d.purchases.map(x=>[esc(date(x.created_at)),esc(x.product_id),esc(x.platform),num(x.coin_granted),num(x.price_try),esc(purchaseState(x.status))]));
    if(state.tab==='account')c.innerHTML=`<dl class="key-values">${Object.entries({'UUID':p.id,'Kayıt tarihi':date(p.created_at),'Son görülme':date(p.last_seen_at),'E-posta':p.email??'Bu role kapalı','Ajans':d.agencies.map(x=>x.name+' · '+x.role).join(', ')||'Yok','Aile':d.families.map(x=>x.name+' · '+x.role).join(', ')||'Yok','VIP bitişi':date(p.vip_expires_at),'Hesap silme talebi':date(p.deletion_requested_at),'Anonimleştirme':p.deletion_requested_at?'14 günlük otomatik süreç; talep kullanıcı tarafından iptal edilebilir.':'Talep yok'}).map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`;
    if(state.tab==='devices')c.innerHTML=`<p class="note">${num(d.devices.count)} kayıtlı cihaz. Kimlikler yalnız Super Admin yetkisiyle gösterilir.</p>`+(d.devices.rows?table(['Cihaz','İlk görülme','Son görülme','Ban'],d.devices.rows.map(x=>[esc(x.device_id),esc(date(x.first_seen)),esc(date(x.last_seen)),x.banli?'Banlı':'—'])):'');
    if(state.tab==='moderation')c.innerHTML='<h3>Güncel platform banı</h3>'+table(['Başlangıç','Bitiş','Sebep'],d.bans.map(x=>[esc(date(x.created_at)),x.expires_at?esc(date(x.expires_at)):'Süresiz',esc(x.reason||'—')]))+'<h3>İşlem kütüğü</h3>'+table(['Zaman','Eylem','Yönetici','Ayrıntı'],d.moderation.map(x=>[esc(date(x.created_at)),esc(x.action),esc(x.actor_id||'Sistem'),`<details><summary>Göster</summary><pre>${esc(JSON.stringify({before:x.previous_state,after:x.new_state},null,2))}</pre></details>`]));
    if(state.tab==='moderation')window.PuffyPhase2?.renderStatus({...phase2Context(),root:c});
  }
  function phase2Context(){return {profile:state.detail?.profile,caps:state.caps,user:state.user,esc,rpc,toast,errorText,date,safeUrl,refresh:async()=>{if(state.route==='kullanici/'+state.detail?.profile.id)await detail(state.detail.profile.id);},invoke:async(name,body)=>{const session=await state.sb.auth.getSession();const token=session.data.session?.access_token;if(!token)throw new Error('NOT_AUTHENTICATED');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(state.sb.supabaseUrl+'/functions/v1/'+name,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,apikey:state.sb.supabaseKey},body:JSON.stringify(body),signal:controller.signal});const payload=await response.json();if(!response.ok||payload.error)throw new Error(payload.error||'SERVER_ERROR');return payload;}finally{clearTimeout(timer);}}};}
  function openActionSheet() {
    const aside=$('#s-kullanici .action-list');if(!aside)return;
    const parent=aside.parentNode,sheet=document.createElement('dialog');sheet.className='actions-sheet';sheet.setAttribute('aria-labelledby','actions-sheet-title');
    sheet.innerHTML='<div class="sheet-handle" aria-hidden="true"></div><div class="panel-head"><div><div class="eyebrow">Hesap yönetimi</div><h2 id="actions-sheet-title">İşlemler</h2></div><button type="button" aria-label="İşlemleri kapat">×</button></div>';
    sheet.append(aside);document.body.append(sheet);sheet.querySelector('[aria-label="İşlemleri kapat"]').onclick=()=>sheet.close();
    sheet.addEventListener('close',()=>{if(parent.isConnected)parent.append(aside);sheet.remove();});sheet.showModal();
  }
  const input = (name,label,type='text',extra='') => `<label for="action-${name}">${label}</label><input id="action-${name}" name="${name}" type="${type}" ${extra}>`;
  async function action(kind) {
    const p=state.detail?.profile;if(!p)return;
    if(await window.PuffyPhase2?.action(kind,phase2Context()))return;
    if(kind==='ownerHistory')return ownerHistory(p);
    const spec={ban:['Hesabı banla',input('hours','Süre · saat (süresiz için 0)','number','min="0" max="8760" value="24" required')],unban:['Banı kaldır',''],deviceBan:['Cihaz banı','<p class="danger-note">Bu cihazdaki diğer hesapların erişimi de etkilenebilir.</p>'],displayId:['Özel ID değiştir',input('id','Yeni ID','text','inputmode="numeric" pattern="[0-9]+" required')],kyc:['KYC doğrulaması','<p>Bu hesabın doğrulamasını onaylayacaksın.</p>'],dealer:['Bayi durumu',`<label for="action-dealer">Yeni durum</label><select id="action-dealer" name="dealer"><option value="true" ${p.is_coin_dealer?'selected':''}>Bayi</option><option value="false" ${!p.is_coin_dealer?'selected':''}>Bayi değil</option></select>`],role:['Personel rolleri',[1,2,3].map((n)=>`<label for="role-${n}">${n}. rol</label><select id="role-${n}" name="role${n}"><option value="">Rol yok</option>${roles.map(r=>`<option value="${r}" ${p[n===1?'staff_role':'staff_role_'+n]===r?'selected':''}>${roleName(r)}</option>`).join('')}</select>`).join('')],grant:['Coin gönder',input('amount','Coin miktarı','number','min="1" max="50000000" step="1" required')],clawback:['Coin geri çek',input('amount','Coin miktarı','number','min="1" max="50000000" step="1" required')],vip:['VIP paketi ver',input('tier','VIP kademesi','number','min="1" max="10" step="1" required')+input('days','Gün','number','min="1" step="1" required')]}[kind];
    if(!spec)return; const owner=['grant','clawback','vip'].includes(kind);const needsReason=!['unban','role','kyc'].includes(kind);if(owner&&!state.caps.owner)return;
    const dlg=document.createElement('dialog');dlg.setAttribute('aria-label',spec[0]);dlg.innerHTML=`<form><h2>${spec[0]}</h2><p>${esc(p.nickname)} · ID ${esc(p.display_id)}<br>Hedef: ${esc(p.id)}</p>${spec[1]}${needsReason?'<label for="action-reason">İşlem sebebi</label><textarea id="action-reason" name="reason" minlength="3" maxlength="300" required placeholder="En az 3 karakter"></textarea>':''}${owner?input('password','Ödeme şifresi','password','required autocomplete="off"'):''}<p class="danger-note">Onayladığında işlem sunucuda uygulanır.</p><div class="dialog-error" role="alert"></div><div class="dialog-actions"><button type="button" data-cancel>Vazgeç</button><button class="primary" type="submit">Onayla ve uygula</button></div></form>`;document.body.append(dlg);dlg.addEventListener('close',()=>dlg.remove());dlg.querySelector('[data-cancel]').onclick=()=>dlg.close();dlg.showModal();let busy=false;
    dlg.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
    dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.target),reason=String(f.get('reason')||'').trim(),err=dlg.querySelector('.dialog-error');if(needsReason&&reason.length<3){err.textContent='En az 3 karakterlik sebep yaz.';return;}const values=[f.get('role1'),f.get('role2'),f.get('role3')].filter(Boolean);if(kind==='role'&&new Set(values).size!==values.length){err.textContent='Aynı rolü iki kez seçemezsin.';return;}
      const calls={ban:['moderator_ban_user',{p_user:p.id,p_hours:Number(f.get('hours'))===0?null:Number(f.get('hours')),p_reason:reason}],unban:['moderator_bani_kaldir',{p_user:p.id}],deviceBan:['moderator_ban_device',{p_user:p.id,p_reason:reason}],displayId:['admin_assign_display_id',{target_user_id:p.id,new_display_id:f.get('id'),reason}],kyc:['admin_verify_kyc',{p_user_id:p.id}],dealer:['admin_set_dealer',{p_user_id:p.id,p_is_dealer:f.get('dealer')==='true',p_reason:reason}],role:['set_staff_role',{p_user:p.id,p_role:f.get('role1')||null,p_role_2:f.get('role2')||null,p_role_3:f.get('role3')||null}],grant:['platform_coin_islemi',{p_hedef:p.id,p_yon:'gonder',p_miktar:Number(f.get('amount')),p_neden:reason,p_odeme_sifresi:f.get('password')}],clawback:['platform_coin_islemi',{p_hedef:p.id,p_yon:'geri_cek',p_miktar:Number(f.get('amount')),p_neden:reason,p_odeme_sifresi:f.get('password')}],vip:['platform_vip_ver',{p_hedef:p.id,p_tier:Number(f.get('tier')),p_gun:Number(f.get('days')),p_neden:reason,p_odeme_sifresi:f.get('password')}]};
      busy=true;dlg.querySelectorAll('button').forEach(b=>b.disabled=true);err.textContent='';
      try {await rpc(...calls[kind]);dlg.close();toast('İşlem sunucu tarafından tamamlandı.');if(state.route==='kullanici/'+p.id)await detail(p.id);if(p.id===state.user?.id){const access=await authorize(state.sb,state.user);state.caps=access.caps;if(!access.allowed){await state.sb.auth.signOut({scope:'local'});close();}else open({sb:state.sb,user:state.user,caps:access.caps});}}
      catch(ex){err.textContent=errorText(ex);busy=false;dlg.querySelectorAll('button').forEach(b=>b.disabled=false);dlg.querySelector('[name=password]')?.focus();}
    };
  }
  async function ownerHistory(p) {
    const dlg=document.createElement('dialog');dlg.innerHTML=`<h2>Kasa geçmişi</h2><p>${esc(p.nickname)}</p><div id="owner-history"></div><div class="dialog-actions"><button>Kapat</button></div>`;document.body.append(dlg);dlg.addEventListener('close',()=>dlg.remove());dlg.querySelector('button').onclick=()=>dlg.close();dlg.showModal();const root=dlg.querySelector('#owner-history');skeleton(root);
    try {const rows=await rpc('platform_coin_hareketleri',{p_hedef:p.id,p_limit:60});if(!dlg.open)return;root.innerHTML=table(['Zaman','Yön','Coin','Sebep','Geri al'],(rows||[]).map(x=>[esc(date(x.created_at)),esc(ledgerName(x.tur)),num(x.miktar),esc(x.referans),!x.geri_alinabilir?(x.geri_alindi?'Geri alındı':'—'):`<button data-reverse="${esc(x.id)}">Geri al</button>`]));root.querySelectorAll('[data-reverse]').forEach(b=>b.onclick=()=>reverseCoin(b.dataset.reverse,dlg,p));}catch(e){pending(root,e,()=>{dlg.close();ownerHistory(p);});}
  }
  function reverseCoin(id,parent,p){const dlg=document.createElement('dialog');dlg.innerHTML=`<form><h2>Coin işlemini geri al</h2><p>${esc(p.nickname)} · İşlem ${esc(id)}</p><label for="reverse-reason">Sebep</label><textarea id="reverse-reason" name="reason" required minlength="3" maxlength="300"></textarea>${input('password','Ödeme şifresi','password','required autocomplete="off"')}<div class="dialog-error" role="alert"></div><div class="dialog-actions"><button type="button">Vazgeç</button><button type="submit" class="primary">Geri almayı onayla</button></div></form>`;document.body.append(dlg);dlg.showModal();dlg.addEventListener('close',()=>dlg.remove());dlg.querySelector('button[type=button]').onclick=()=>dlg.close();let busy=false;dlg.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dlg.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.target);busy=true;dlg.querySelectorAll('button').forEach(b=>b.disabled=true);try{await rpc('platform_coin_geri_al',{p_hareket_id:id,p_neden:String(f.get('reason')).trim(),p_odeme_sifresi:f.get('password'),p_kismi:false});dlg.close();parent.close();toast('İşlem geri alındı.');if(state.route==='kullanici/'+p.id)detail(p.id);}catch(ex){dlg.querySelector('.dialog-error').textContent=errorText(ex);busy=false;dlg.querySelectorAll('button').forEach(b=>b.disabled=false);}};}
  async function staff() {const root=$('#s-personel'),epoch=++state.epoch;root.innerHTML=title('Erişim yönetimi','Personel ve yetki','Mevcut üç rol slotunu kullanarak yetki ver veya kaldır.')+'<div class="panel" id="staff-list"></div>';const box=$('#staff-list');skeleton(box);try{const rows=await rpc('personel_listesi');if(epoch!==state.epoch)return;box.innerHTML=table(['Personel','Roller','Platform yöneticisi'],(rows||[]).map(p=>[`<div class="person">${avatar(p)}<div><a href="#kullanici/${esc(p.user_id)}">${esc(p.nickname)}</a><small>ID ${esc(p.display_id)}</small></div></div>`,[p.staff_role,p.staff_role_2,p.staff_role_3].filter(Boolean).map(r=>`<span class="tag">${esc(roleName(r))}</span>`).join(''),p.platform_admin?'Evet':'Hayır']));bindAvatars(box);}catch(e){if(epoch===state.epoch)pending(box,e,staff);}}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#uyg nav')?.classList.remove('open');$('#panel-topbar .mobile-menu')?.setAttribute('aria-expanded','false');}});
  window.PuffyPhase1={authorize,open,route,close};
})();
